---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "referencedata-service.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "{{ .Values.service.hostname }}.{{ .Release.Name }}.does.not.exist"
  rules:
  - host: "{{ .Values.service.hostname }}.{{ .Release.Name }}.does.not.exist"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-{{ include "referencedata-service.name" . }}"
          servicePort: {{ .Values.service.port }}
