---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: {{ include "referencedata-service.name" . }}-{{ .Values.service.bbApiVersion }}
  labels:
    app: {{ include "referencedata-service.name" . }}-{{ .Values.service.bbApiVersion }}
    k8s-app: {{ include "referencedata-service.name" . }}-{{ .Values.service.bbApiVersion }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "referencedata-service.name" . }}-{{ .Values.service.bbApiVersion }}
  endpoints:
    - port: springbootadmin
      scheme: http
      path: '/manage/actuator/prometheus'
      interval: 15s
      honorLabels: true

