blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth
  reference-data-service:
    service-host:
      host: referencedata-service

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/bb_dev?currentSchema=referencedata
