management:
  server:
    port: ${bb_health:8081}

blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database}?currentSchema=referencedata&sslmode=verify-full

server:
  port: ${bb_port:8080}
