management:
  server:
    port: ${bb_health:-8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database:-bb_dev}?currentSchema=referencedata&sslmode=verify-full

server:
  port: ${bb_port:-8080}
  servlet:
    context-path: /uk-gov-dft/reference-data-service/1.0.0

