blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://postgresql:5432/bb_dev?currentSchema=referencedata&sslmode=require
