
logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}

management:
  server:
    port: ${bb_health:-8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.referencedata.repository.domain

spring:
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.does.not.exist:5432/${bb_database:-bb_dev}?currentSchema=referencedata
  jackson:
    date-format: uk.gov.dft.bluebadge.service.referencedata.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${bb_port:-8080}
  servlet:
    context-path: /uk-gov-dft/reference-data-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs
