replicaCount: 2

image:
  repository: 536084723381.dkr.ecr.eu-west-2.amazonaws.com/uk-gov-dft/referencedata-service
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# The hostname portion of the DNS hostname in R53
service:
  hostname: reference-service
  type: ClusterIP
  port: 8080

adminservice:
  type: ClusterIP
  port: 8081
  path: '/manage/actuator/info'

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
