update referencedata.reference_data set meta_data = meta_data::JSONB || '{"isActive":true}' where data_group_id = 'LC' and code in
(
'BRID', 'CAER', 'ESUCC', 'EAS', 'HAS', 'LEE', 'ROH', 'WEA', 'GLOCC',
'CHT', 'COT', 'FOE', 'GLS', 'STO', 'TEW', 'ANGL', 'LBEAL', 'NELIN', 'ABERD',
'EAYR', 'SLAN', 'WDUN', 'WLOTH', 'WAKE', 'WORCC', 'BRM', 'MAV', 'RED', 'WOC',
'WYC', 'WYE', 'NWA', 'NUN', 'RUG', 'STR', 'WAW', 'WARCC', 'BAB', 'FOR',
'IPS', 'MSU', 'SED', 'SUF', 'SUFCC', 'WAV', 'BARNS'
);

update referencedata.reference_data set meta_data = meta_data::JSONB || '{"isActive":false}' where data_group_id = 'LC' and code in (
'KENTCC', 'ASF', 'CAT', 'DAR', 'DOV', 'SHE', 'GRA', 'MAI', 'SEV', 'SWL', 'THA', 'TON', 'TUN', 'NAYR'
);

insert into referencedata.reference_data(data_group_id, code, description, data_subgroup_id, meta_data) VALUES
('LC', 'ABERC',  'Aberdeen city council', null, '{"issuingAuthorityShortCode":"ABERC", "isActive": false }')
,('LC', 'ANGUS', 'Angus council', null, '{"issuingAuthorityShortCode":"ANGUS", "isActive": false }')
,('LC', 'ARBUT', 'Argyll and Bute council', null, '{"issuingAuthorityShortCode":"ARBUT", "isActive": false }')
,('LC', 'BEDF', 'Bedford borough council', null, '{"issuingAuthorityShortCode":"BEDF", "isActive": false }')
,('LC', 'BIRM', 'Birmingham city council', null, '{"issuingAuthorityShortCode":"BIRM", "isActive": false }')
,('LC', 'BLACK', 'Blackpool borough council', null, '{"issuingAuthorityShortCode":"BLACK", "isActive": false }')
,('LC', 'BLDRN', 'Blackburn with Darwen borough council', null, '{"issuingAuthorityShortCode":"BLDRN", "isActive": false }')
,('LC', 'BLGW', 'Blaenau Gwent county borough council', null, '{"issuingAuthorityShortCode":"BLGW", "isActive": false }')
,('LC', 'BOLT', 'Bolton metropolitan borough council', null, '{"issuingAuthorityShortCode":"BOLT", "isActive": false }')
,('LC', 'BOURN', 'Bournemouth borough council', null, '{"issuingAuthorityShortCode":"BOURN", "isActive": false }')
,('LC', 'BRAD', 'City of Bradford metropolitan district council', null, '{"issuingAuthorityShortCode":"BRAD", "isActive": false }')
,('LC', 'BRAFR', 'Bracknell Forest council', null, '{"issuingAuthorityShortCode":"BRAFR", "isActive": false }')
,('LC', 'BRIHV', 'Brighton and Hove city council', null, '{"issuingAuthorityShortCode":"BRIHV", "isActive": false }')
,('LC', 'BRIST', 'Bristol city council', null, '{"issuingAuthorityShortCode":"BRIST", "isActive": false }')
,('LC', 'BTNES', 'Bath and North East Somerset council', null, '{"issuingAuthorityShortCode":"BTNES", "isActive": false }')
,('LC', 'AYL', 'Aylesbury Vale district council', null, '{"issuingAuthorityShortCode":"BUCCC", "isActive": false }')
,('LC', 'BUCCC', 'Buckinghamshire county council', null, '{"issuingAuthorityShortCode":"BUCCC", "isActive": false }')
,('LC', 'CHN', 'Chiltern district council', null, '{"issuingAuthorityShortCode":"BUCCC", "isActive": false }')
,('LC', 'SBU', 'South bucks district council', null, '{"issuingAuthorityShortCode":"BUCCC", "isActive": false }')
,('LC', 'WYO', 'Wycombe district council', null, '{"issuingAuthorityShortCode":"BUCCC", "isActive": false }')
,('LC', 'BURY', 'Bury metropolitan borough council', null, '{"issuingAuthorityShortCode":"BURY", "isActive": false }')
,('LC', 'CALD', 'Calderdale metropolitan borough council', null, '{"issuingAuthorityShortCode":"CALD", "isActive": false }')
,('LC', 'CAB', 'Cambridge city council', null, '{"issuingAuthorityShortCode":"CAMCC", "isActive": false }')
,('LC', 'CAMCC', 'Cambridgeshire county council', null, '{"issuingAuthorityShortCode":"CAMCC", "isActive": false }')
,('LC', 'ECA', 'East Cambridgeshire district council', null, '{"issuingAuthorityShortCode":"CAMCC", "isActive": false }')
,('LC', 'FEN', 'Fenland district council', null, '{"issuingAuthorityShortCode":"CAMCC", "isActive": false }')
,('LC', 'HUN', 'Huntingdonshire district council', null, '{"issuingAuthorityShortCode":"CAMCC", "isActive": false }')
,('LC', 'SCA', 'South Cambridgeshire district council', null, '{"issuingAuthorityShortCode":"CAMCC", "isActive": false }')
,('LC', 'CARD', 'City of Cardiff council', null, '{"issuingAuthorityShortCode":"CARD", "isActive": false }')
,('LC', 'CARM', 'Carmarthenshire county council', null, '{"issuingAuthorityShortCode":"CARM", "isActive": false }')
,('LC', 'CBED', 'Central Bedfordshire council', null, '{"issuingAuthorityShortCode":"CBED", "isActive": false }')
,('LC', 'CERE', 'Ceredigion county council', null, '{"issuingAuthorityShortCode":"CERE", "isActive": false }')
,('LC', 'CHESE', 'Cheshire East council', null, '{"issuingAuthorityShortCode":"CHESE", "isActive": false }')
,('LC', 'CHEWC', 'Cheshire West and Chester council', null, '{"issuingAuthorityShortCode":"CHEWC", "isActive": false }')
,('LC', 'CLACK', 'Clackmannanshire council', null, '{"issuingAuthorityShortCode":"CLACK", "isActive": false }')
,('LC', 'CONWY', 'Conwy county borough council', null, '{"issuingAuthorityShortCode":"CONWY", "isActive": false }')
,('LC', 'CORN', 'Cornwall council', null, '{"issuingAuthorityShortCode":"CORN", "isActive": false }')
,('LC', 'COV', 'Coventry city council', null, '{"issuingAuthorityShortCode":"COV", "isActive": false }')
,('LC', 'ALL', 'Allerdale borough council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'BAR', 'Barrow-in-Furness borough council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'CAR', 'Carlisle city council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'COP', 'Copeland borough council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'CUMCC', 'Cumbria county council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'EDN', 'Eden district council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'SLA', 'South Lakeland district council', null, '{"issuingAuthorityShortCode":"CUMCC", "isActive": false }')
,('LC', 'DARL', 'Darlington borough council', null, '{"issuingAuthorityShortCode":"DARL", "isActive": false }')
,('LC', 'DENB', 'Denbighshire county council', null, '{"issuingAuthorityShortCode":"DENB", "isActive": false }')
,('LC', 'DERBY', 'Derby city council', null, '{"issuingAuthorityShortCode":"DERBY", "isActive": false }')
,('LC', 'AMB', 'Amber Valley borough council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'BOS', 'Bolsover district council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'CHS', 'Chesterfield borough council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'DERCC', 'Derbyshire county council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'DEB', 'Derbyshire Dales district council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'ERE', 'Erewash borough council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'HIG', 'High Peak borough council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'NED', 'North East Derbyshire district council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'SDE', 'South Derbyshire district council', null, '{"issuingAuthorityShortCode":"DERCC", "isActive": false }')
,('LC', 'DEVCC', 'Devon county council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'EDE', 'East Devon district council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'EXE', 'Exeter city council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'MDE', 'Mid Devon district council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'NDE', 'North Devon district council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'SHA', 'South Hams district council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'TEI', 'Teignbridge district council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'TOR', 'Torridge district council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'WDE', 'West Devon borough council', null, '{"issuingAuthorityShortCode":"DEVCC", "isActive": false }')
,('LC', 'DONC', 'Doncaster metropolitan borough council', null, '{"issuingAuthorityShortCode":"DONC", "isActive": false }')
,('LC', 'CHC', 'Christchurch borough council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'DORCC', 'Dorset county council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'EDO', 'East Dorset district council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'NDO', 'North Dorset district council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'PUR', 'Purbeck district council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'WDO', 'West Dorset district council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'WEY', 'Weymouth and Portland borough council', null, '{"issuingAuthorityShortCode":"DORCC", "isActive": false }')
,('LC', 'DUDL', 'Dudley metropolitan borough council', null, '{"issuingAuthorityShortCode":"DUDL", "isActive": false }')
,('LC', 'DUMGL', 'Dumfries and Galloway council', null, '{"issuingAuthorityShortCode":"DUMGL", "isActive": false }')
,('LC', 'DUNDC', 'Dundee city council', null, '{"issuingAuthorityShortCode":"DUNDC", "isActive": false }')
,('LC', 'DURHM', 'Durham county council', null, '{"issuingAuthorityShortCode":"DURHM", "isActive": false }')
,('LC', 'EDIN', 'City of Edinburgh council', null, '{"issuingAuthorityShortCode":"EDIN", "isActive": false }')
,('LC', 'EDUN', 'East Dunbartonshire council', null, '{"issuingAuthorityShortCode":"EDUN", "isActive": false }')
,('LC', 'EILSR', 'Comhairle nan Eilean Siar', null, '{"issuingAuthorityShortCode":"EILSR", "isActive": false }')
,('LC', 'ELOTH', 'East Lothian council', null, '{"issuingAuthorityShortCode":"ELOTH", "isActive": false }')
,('LC', 'EREN', 'East Renfrewshire council', null, '{"issuingAuthorityShortCode":"EREN", "isActive": false }')
,('LC', 'BAI', 'Basildon borough council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'BRA', 'Braintree district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'BRW', 'Brentwood borough council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'CAS', 'Castle Point borough council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'CHL', 'Chelmsford city council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'COL', 'Colchester borough council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'EPP', 'Epping Forest district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'ESSCC', 'Essex county council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'HAR', 'Harlow district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'MAL', 'Maldon district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'ROC', 'Rochford district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'TEN', 'Tendring district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'UTT', 'Uttlesford district council', null, '{"issuingAuthorityShortCode":"ESSCC", "isActive": false }')
,('LC', 'EYORK', 'East Riding of Yorkshire council', null, '{"issuingAuthorityShortCode":"EYORK", "isActive": false }')
,('LC', 'FALK', 'Falkirk council', null, '{"issuingAuthorityShortCode":"FALK", "isActive": false }')
,('LC', 'FIFE', 'Fife council', null, '{"issuingAuthorityShortCode":"FIFE", "isActive": false }')
,('LC', 'FLINT', 'Flintshire county council', null, '{"issuingAuthorityShortCode":"FLINT", "isActive": false }')
,('LC', 'GATES', 'Gateshead metropolitan borough council', null, '{"issuingAuthorityShortCode":"GATES", "isActive": false }')
,('LC', 'GLAM', 'Vale of Glamorgan council', null, '{"issuingAuthorityShortCode":"GLAM", "isActive": false }')
,('LC', 'GLAS', 'Glasgow city council', null, '{"issuingAuthorityShortCode":"GLAS", "isActive": false }')
,('LC', 'GWYN', 'Gwynedd council', null, '{"issuingAuthorityShortCode":"GWYN", "isActive": false }')
,('LC', 'HALT', 'Halton borough council', null, '{"issuingAuthorityShortCode":"HALT", "isActive": false }')
,('LC', 'BAN', 'Basingstoke and Deane borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'EHA', 'East Hampshire district council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'EAT', 'Eastleigh borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'FAR', 'Fareham borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'GOS', 'Gosport borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'HAMCC', 'Hampshire county council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'HAT', 'Hart district council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'HAA', 'Havant borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'NEW', 'New Forest district council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'RUH', 'Rushmoor borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'TES', 'Test Valley borough council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'WIN', 'Winchester city council', null, '{"issuingAuthorityShortCode":"HAMCC", "isActive": false }')
,('LC', 'HART', 'Hartlepool borough council', null, '{"issuingAuthorityShortCode":"HART", "isActive": false }')
,('LC', 'BRX', 'Broxbourne borough council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'DAC', 'Dacorum borough council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'EHE', 'East Hertfordshire district council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'HERCC', 'Hertfordshire county council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'HER', 'Hertsmere borough council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'NHE', 'North Hertfordshire district council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'SAL', 'St Albans city and district council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'STV', 'Stevenage borough council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'THE', 'Three Rivers district council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'WAT', 'Watford borough council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'WEW', 'Welwyn Hatfield borough council', null, '{"issuingAuthorityShortCode":"HERCC", "isActive": false }')
,('LC', 'HEREF', 'Herefordshire council', null, '{"issuingAuthorityShortCode":"HEREF", "isActive": false }')
,('LC', 'HIGH', 'Highland council', null, '{"issuingAuthorityShortCode":"HIGH", "isActive": false }')
,('LC', 'HULL', 'Hull city council', null, '{"issuingAuthorityShortCode":"HULL", "isActive": false }')
,('LC', 'INVC', 'Inverclyde council', null, '{"issuingAuthorityShortCode":"INVC", "isActive": false }')
,('LC', 'IOS', 'Council of the Isles of Scilly', null, '{"issuingAuthorityShortCode":"IOS", "isActive": false }')
,('LC', 'IOW', 'Isle of Wight council', null, '{"issuingAuthorityShortCode":"IOW", "isActive": false }')
,('LC', 'KIRK', 'Kirklees council', null, '{"issuingAuthorityShortCode":"KIRK", "isActive": false }')
,('LC', 'KNOWS', 'Knowsley metropolitan borough council', null, '{"issuingAuthorityShortCode":"KNOWS", "isActive": false }')
,('LC', 'BUN', 'Burnley borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'CHO', 'Chorley borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'FYL', 'Fylde borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'HYN', 'Hyndburn borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'LANCC', 'Lancashire county council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'LAC', 'Lancaster city council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'PEN', 'Pendle borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'PRE', 'Preston city council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'RIB', 'Ribble valley borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'ROS', 'Rossendale borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'SRI', 'South Ribble borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'WLA', 'West Lancashire borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'WYR', 'Wyre borough council', null, '{"issuingAuthorityShortCode":"LANCC", "isActive": false }')
,('LC', 'LBBAD', 'London borough of Barking and Dagenham', null, '{"issuingAuthorityShortCode":"LBBAD", "isActive": false }')
,('LC', 'LBBAR', 'London borough of Barnet', null, '{"issuingAuthorityShortCode":"LBBAR", "isActive": false }')
,('LC', 'LBBEX', 'London borough of Bexley', null, '{"issuingAuthorityShortCode":"LBBEX", "isActive": false }')
,('LC', 'LBBRE', 'London borough of Brent', null, '{"issuingAuthorityShortCode":"LBBRE", "isActive": false }')
,('LC', 'LBBRO', 'London borough of Bromley', null, '{"issuingAuthorityShortCode":"LBBRO", "isActive": false }')
,('LC', 'LBCAM', 'London borough of Camden', null, '{"issuingAuthorityShortCode":"LBCAM", "isActive": false }')
,('LC', 'LBCOL', 'City of London Corporation', null, '{"issuingAuthorityShortCode":"LBCOL", "isActive": false }')
,('LC', 'LBCRO', 'London borough of Croydon', null, '{"issuingAuthorityShortCode":"LBCRO", "isActive": false }')
,('LC', 'LBENF', 'London borough of Enfield', null, '{"issuingAuthorityShortCode":"LBENF", "isActive": false }')
,('LC', 'LBGRE', 'Royal borough of Greenwich', null, '{"issuingAuthorityShortCode":"LBGRE", "isActive": false }')
,('LC', 'LBHAC', 'London borough of Hackney', null, '{"issuingAuthorityShortCode":"LBHAC", "isActive": false }')
,('LC', 'LBHAF', 'London borough of Hammersmith and Fulham', null, '{"issuingAuthorityShortCode":"LBHAF", "isActive": false }')
,('LC', 'LBHAV', 'London borough of Havering', null, '{"issuingAuthorityShortCode":"LBHAV", "isActive": false }')
,('LC', 'LBHGY', 'London borough of Haringey', null, '{"issuingAuthorityShortCode":"LBHGY", "isActive": false }')
,('LC', 'LBHIL', 'London borough of Hillingdon', null, '{"issuingAuthorityShortCode":"LBHIL", "isActive": false }')
,('LC', 'LBHOW', 'London borough of Hounslow', null, '{"issuingAuthorityShortCode":"LBHOW", "isActive": false }')
,('LC', 'LBHRW', 'London borough of Harrow', null, '{"issuingAuthorityShortCode":"LBHRW", "isActive": false }')
,('LC', 'LBISL', 'London borough of Islington', null, '{"issuingAuthorityShortCode":"LBISL", "isActive": false }')
,('LC', 'LBKC', 'Royal borough of Kensington and Chelsea', null, '{"issuingAuthorityShortCode":"LBKC", "isActive": false }')
,('LC', 'LBKUT', 'Royal borough of Kingston upon Thames', null, '{"issuingAuthorityShortCode":"LBKUT", "isActive": false }')
,('LC', 'LBLAM', 'London borough of Lambeth', null, '{"issuingAuthorityShortCode":"LBLAM", "isActive": false }')
,('LC', 'LBLEW', 'London borough of Lewisham', null, '{"issuingAuthorityShortCode":"LBLEW", "isActive": false }')
,('LC', 'LBMER', 'London borough of Merton', null, '{"issuingAuthorityShortCode":"LBMER", "isActive": false }')
,('LC', 'LBNEW', 'London borough of Newham', null, '{"issuingAuthorityShortCode":"LBNEW", "isActive": false }')
,('LC', 'LBRED', 'London borough of Redbridge', null, '{"issuingAuthorityShortCode":"LBRED", "isActive": false }')
,('LC', 'LBRIC', 'London borough of Richmond upon Thames', null, '{"issuingAuthorityShortCode":"LBRIC", "isActive": false }')
,('LC', 'LBSOU', 'London borough of Southwark', null, '{"issuingAuthorityShortCode":"LBSOU", "isActive": false }')
,('LC', 'LBSUT', 'London borough of Sutton', null, '{"issuingAuthorityShortCode":"LBSUT", "isActive": false }')
,('LC', 'LBTHA', 'London borough of Tower Hamlets', null, '{"issuingAuthorityShortCode":"LBTHA", "isActive": false }')
,('LC', 'LBWAL', 'London borough of Waltham Forest', null, '{"issuingAuthorityShortCode":"LBWAL", "isActive": false }')
,('LC', 'LBWAN', 'London borough of Wandsworth', null, '{"issuingAuthorityShortCode":"LBWAN", "isActive": false }')
,('LC', 'LBWES', 'City of Westminster', null, '{"issuingAuthorityShortCode":"LBWES", "isActive": false }')
,('LC', 'LEEDS', 'Leeds city council', null, '{"issuingAuthorityShortCode":"LEEDS", "isActive": false }')
,('LC', 'LEIC', 'Leicester city council', null, '{"issuingAuthorityShortCode":"LEIC", "isActive": false }')
,('LC', 'BLA', 'Blaby district council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'CHA', 'Charnwood borough council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'HAO', 'Harborough district council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'HIN', 'Hinckley and bosworth borough council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'LEICC', 'Leicestershire county council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'MEL', 'Melton borough council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'NWL', 'North west leicestershire district council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'OAD', 'Oadby and Wigston borough council', null, '{"issuingAuthorityShortCode":"LEICC", "isActive": false }')
,('LC', 'BOT', 'Boston borough council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'LIC', 'City of Lincoln council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'ELI', 'East Lindsey district council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'LINCC', 'Lincolnshire county council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'NKE', 'North Kesteven district council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'SHO', 'South Holland district council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'SKE', 'South Kesteven district council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'WLI', 'West Lindsey district council', null, '{"issuingAuthorityShortCode":"LINCC", "isActive": false }')
,('LC', 'LIVER', 'Liverpool city council', null, '{"issuingAuthorityShortCode":"LIVER", "isActive": false }')
,('LC', 'LUTON', 'Luton borough council', null, '{"issuingAuthorityShortCode":"LUTON", "isActive": false }')
,('LC', 'MANC', 'Manchester city council', null, '{"issuingAuthorityShortCode":"MANC", "isActive": false }')
,('LC', 'MEDTN', 'Medway council', null, '{"issuingAuthorityShortCode":"MEDTN", "isActive": false }')
,('LC', 'MERTH', 'Merthyr Tydfil county borough council', null, '{"issuingAuthorityShortCode":"MERTH", "isActive": false }')
,('LC', 'MIDDL', 'Middlesbrough borough council', null, '{"issuingAuthorityShortCode":"MIDDL", "isActive": false }')
,('LC', 'MIDLH', 'Midlothian council', null, '{"issuingAuthorityShortCode":"MIDLH", "isActive": false }')
,('LC', 'MILKN', 'Milton Keynes council', null, '{"issuingAuthorityShortCode":"MILKN", "isActive": false }')
,('LC', 'MON', 'Monmouthshire county council', null, '{"issuingAuthorityShortCode":"MON", "isActive": false }')
,('LC', 'MORAY', 'Moray council', null, '{"issuingAuthorityShortCode":"MORAY", "isActive": false }')
,('LC', 'NEATH', 'Neath Port Talbot county borough council', null, '{"issuingAuthorityShortCode":"NEATH", "isActive": false }')
,('LC', 'NEWC', 'Newcastle city council', null, '{"issuingAuthorityShortCode":"NEWC", "isActive": false }')
,('LC', 'NEWP', 'Newport city council', null, '{"issuingAuthorityShortCode":"NEWP", "isActive": false }')
,('LC', 'ANN', 'Antrim and Newtownabbey borough council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'AND', 'Ards and North Down borough council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'ABC', 'Armagh city, Banbridge and Craigavon borough council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'BFS', 'Belfast city council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'CCG', 'Causeway coast and Glens borough council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'DRS', 'Derry city and Strabane district council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'FMO', 'Fermanagh and Omagh district council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'LBC', 'Lisburn and Castlereagh city council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'MEA', 'Mid and East Antrim borough council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'MUL', 'Mid Ulster district council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'NIRE', 'Northern Ireland', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'NMD', 'Newry, Mourne and Down district council', null, '{"issuingAuthorityShortCode":"NIRE", "isActive": false }')
,('LC', 'NLAN', 'North Lanarkshire council', null, '{"issuingAuthorityShortCode":"NLAN", "isActive": false }')
,('LC', 'NLIN', 'North Lincolnshire council', null, '{"issuingAuthorityShortCode":"NLIN", "isActive": false }')
,('LC', 'KIN', 'Borough council of King''s Lynn and West Norfolk', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'BRE', 'Breckland district council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'BRO', 'Broadland district council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'GRY', 'Great Yarmouth borough council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'NOFCC', 'Norfolk county council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'NNO', 'North Norfolk district council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'NOW', 'Norwich city council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'SNO', 'South Norfolk district council', null, '{"issuingAuthorityShortCode":"NOFCC", "isActive": false }')
,('LC', 'COR', 'Corby borough council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'DAV', 'Daventry district council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'ENO', 'East Northamptonshire council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'KET', 'Kettering borough council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'NOR', 'Northampton borough council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'NORCC', 'Northamptonshire county council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'SNR', 'South Northamptonshire council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'WEL', 'Wellingborough borough council', null, '{"issuingAuthorityShortCode":"NORCC", "isActive": false }')
,('LC', 'NORTH', 'Northumberland county council', null, '{"issuingAuthorityShortCode":"NORTH", "isActive": false }')
,('LC', 'ASH', 'Ashfield district council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'BAE', 'Bassetlaw district council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'BRT', 'Broxtowe borough council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'GED', 'Gedling borough council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'MAS', 'Mansfield district council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'NEA', 'Newark and Sherwood district council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'NOTCC', 'Nottinghamshire county council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'RUS', 'Rushcliffe borough council', null, '{"issuingAuthorityShortCode":"NOTCC", "isActive": false }')
,('LC', 'NOTT', 'Nottingham city council', null, '{"issuingAuthorityShortCode":"NOTT", "isActive": false }')
,('LC', 'NSOM', 'North Somerset council', null, '{"issuingAuthorityShortCode":"NSOM", "isActive": false }')
,('LC', 'NTYNE', 'North Tyneside council', null, '{"issuingAuthorityShortCode":"NTYNE", "isActive": false }')
,('LC', 'CRA', 'Craven district council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'HAE', 'Hambleton district council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'HAG', 'Harrogate borough council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'NYKCC', 'North Yorkshire county council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'RIH', 'Richmondshire district council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'RYE', 'Ryedale district council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'SCE', 'Scarborough borough council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'SEL', 'Selby district council', null, '{"issuingAuthorityShortCode":"NYKCC", "isActive": false }')
,('LC', 'OLDH', 'Oldham metropolitan borough council', null, '{"issuingAuthorityShortCode":"OLDH", "isActive": false }')
,('LC', 'ORKNY', 'Orkney Islands council', null, '{"issuingAuthorityShortCode":"ORKNY", "isActive": false }')
,('LC', 'CHR', 'Cherwell district council', null, '{"issuingAuthorityShortCode":"OXFCC", "isActive": false }')
,('LC', 'OXO', 'Oxford city council', null, '{"issuingAuthorityShortCode":"OXFCC", "isActive": false }')
,('LC', 'OXFCC', 'Oxfordshire county council', null, '{"issuingAuthorityShortCode":"OXFCC", "isActive": false }')
,('LC', 'SOX', 'South Oxfordshire district council', null, '{"issuingAuthorityShortCode":"OXFCC", "isActive": false }')
,('LC', 'VAL', 'Vale of White Horse district council', null, '{"issuingAuthorityShortCode":"OXFCC", "isActive": false }')
,('LC', 'WOX', 'West Oxfordshire district council', null, '{"issuingAuthorityShortCode":"OXFCC", "isActive": false }')
,('LC', 'PEMB', 'Pembrokeshire county council', null, '{"issuingAuthorityShortCode":"PEMB", "isActive": false }')
,('LC', 'PERKN', 'Perth and Kinross council', null, '{"issuingAuthorityShortCode":"PERKN", "isActive": false }')
,('LC', 'PETBR', 'Peterborough city council', null, '{"issuingAuthorityShortCode":"PETBR", "isActive": false }')
,('LC', 'PLYM', 'Plymouth city council', null, '{"issuingAuthorityShortCode":"PLYM", "isActive": false }')
,('LC', 'POOLE', 'Borough of Poole', null, '{"issuingAuthorityShortCode":"POOLE", "isActive": false }')
,('LC', 'PORTS', 'Portsmouth city council', null, '{"issuingAuthorityShortCode":"PORTS", "isActive": false }')
,('LC', 'POWYS', 'Powys county council', null, '{"issuingAuthorityShortCode":"POWYS", "isActive": false }')
,('LC', 'RCT', 'Rhondda Cynon Taf county borough council', null, '{"issuingAuthorityShortCode":"RCT", "isActive": false }')
,('LC', 'READ', 'Reading borough council', null, '{"issuingAuthorityShortCode":"READ", "isActive": false }')
,('LC', 'REDCL', 'Redcar and Cleveland borough council', null, '{"issuingAuthorityShortCode":"REDCL", "isActive": false }')
,('LC', 'RENF', 'Renfrewshire council', null, '{"issuingAuthorityShortCode":"RENF", "isActive": false }')
,('LC', 'ROCH', 'Rochdale metropolitan borough council', null, '{"issuingAuthorityShortCode":"ROCH", "isActive": false }')
,('LC', 'ROTH', 'Rotherham metropolitan borough council', null, '{"issuingAuthorityShortCode":"ROTH", "isActive": false }')
,('LC', 'RUT', 'Rutland county council', null, '{"issuingAuthorityShortCode":"RUT", "isActive": false }')
,('LC', 'SALF', 'Salford city council', null, '{"issuingAuthorityShortCode":"SALF", "isActive": false }')
,('LC', 'SAND', 'Sandwell metropolitan borough council', null, '{"issuingAuthorityShortCode":"SAND", "isActive": false }')
,('LC', 'SAYR', 'South Ayrshire council', null, '{"issuingAuthorityShortCode":"SAYR", "isActive": false }')
,('LC', 'SCBRD', 'Scottish Borders council', null, '{"issuingAuthorityShortCode":"SCBRD", "isActive": false }')
,('LC', 'SEFT', 'Sefton metropolitan borough council', null, '{"issuingAuthorityShortCode":"SEFT", "isActive": false }')
,('LC', 'SEND', 'Southend-on-Sea borough council', null, '{"issuingAuthorityShortCode":"SEND", "isActive": false }')
,('LC', 'SGLCS', 'South Gloucestershire council', null, '{"issuingAuthorityShortCode":"SGLCS", "isActive": false }')
,('LC', 'SHEFF', 'Sheffield city council', null, '{"issuingAuthorityShortCode":"SHEFF", "isActive": false }')
,('LC', 'SHETL', 'Shetland Islands council', null, '{"issuingAuthorityShortCode":"SHETL", "isActive": false }')
,('LC', 'SHROP', 'Shropshire council', null, '{"issuingAuthorityShortCode":"SHROP", "isActive": false }')
,('LC', 'SLGH', 'Slough borough council', null, '{"issuingAuthorityShortCode":"SLGH", "isActive": false }')
,('LC', 'SOLHL', 'Solihull metropolitan borough council', null, '{"issuingAuthorityShortCode":"SOLHL", "isActive": false }')
,('LC', 'MEN', 'Mendip district council', null, '{"issuingAuthorityShortCode":"SOMCC", "isActive": false }')
,('LC', 'SEG', 'Sedgemoor district council', null, '{"issuingAuthorityShortCode":"SOMCC", "isActive": false }')
,('LC', 'SOMCC', 'Somerset county council', null, '{"issuingAuthorityShortCode":"SOMCC", "isActive": false }')
,('LC', 'SSO', 'South Somerset district council', null, '{"issuingAuthorityShortCode":"SOMCC", "isActive": false }')
,('LC', 'TAU', 'Taunton Deane borough council', null, '{"issuingAuthorityShortCode":"SOMCC", "isActive": false }')
,('LC', 'WSO', 'West Somerset district council', null, '{"issuingAuthorityShortCode":"SOMCC", "isActive": false }')
,('LC', 'SOUTH', 'Southampton city council', null, '{"issuingAuthorityShortCode":"SOUTH", "isActive": false }')
,('LC', 'CAN', 'Cannock Chase district council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'EST', 'East Staffordshire borough council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'LIF', 'Lichfield district council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'NEC', 'Newcastle-under-Lyme borough council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'SST', 'South Staffordshire council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'STA', 'Stafford borough council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'STACC', 'Staffordshire county council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'STF', 'Staffordshire Moorlands district council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'TAW', 'Tamworth borough council', null, '{"issuingAuthorityShortCode":"STACC", "isActive": false }')
,('LC', 'STHEL', 'St Helens council', null, '{"issuingAuthorityShortCode":"STHEL", "isActive": false }')
,('LC', 'STIR', 'Stirling council', null, '{"issuingAuthorityShortCode":"STIR", "isActive": false }')
,('LC', 'STOPT', 'Stockport metropolitan borough council', null, '{"issuingAuthorityShortCode":"STOPT", "isActive": false }')
,('LC', 'STOTN', 'Stockton-on-Tees borough council', null, '{"issuingAuthorityShortCode":"STOTN", "isActive": false }')
,('LC', 'STOTR', 'Stoke-on-Trent city council', null, '{"issuingAuthorityShortCode":"STOTR", "isActive": false }')
,('LC', 'STYNE', 'South Tyneside council', null, '{"issuingAuthorityShortCode":"STYNE", "isActive": false }')
,('LC', 'SUND', 'Sunderland city council', null, '{"issuingAuthorityShortCode":"SUND", "isActive": false }')
,('LC', 'ELM', 'Elmbridge borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'EPS', 'Epsom and Ewell borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'GRT', 'Guildford borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'MOL', 'Mole Valley district council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'REI', 'Reigate and Banstead borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'RUN', 'Runnymede borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'SPE', 'Spelthorne borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'SURCC', 'Surrey county council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'SUR', 'Surrey Heath borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'TAN', 'Tandridge district council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'WAE', 'Waverley borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'WOI', 'Woking borough council', null, '{"issuingAuthorityShortCode":"SURCC", "isActive": false }')
,('LC', 'SWAN', 'City and county of Swansea council', null, '{"issuingAuthorityShortCode":"SWAN", "isActive": false }')
,('LC', 'SWIND', 'Swindon borough council', null, '{"issuingAuthorityShortCode":"SWIND", "isActive": false }')
,('LC', 'TAME', 'Tameside metropolitan borough council', null, '{"issuingAuthorityShortCode":"TAME", "isActive": false }')
,('LC', 'TELWK', 'Telford and Wrekin council', null, '{"issuingAuthorityShortCode":"TELWK", "isActive": false }')
,('LC', 'THURK', 'Thurrock council', null, '{"issuingAuthorityShortCode":"THURK", "isActive": false }')
,('LC', 'TORB', 'Torbay council', null, '{"issuingAuthorityShortCode":"TORB", "isActive": false }')
,('LC', 'TORF', 'Torfaen county borough council', null, '{"issuingAuthorityShortCode":"TORF", "isActive": false }')
,('LC', 'TRAF', 'Trafford metropolitan borough council', null, '{"issuingAuthorityShortCode":"TRAF", "isActive": false }')
,('LC', 'WAL', 'Walsall metropolitan borough council', null, '{"issuingAuthorityShortCode":"WAL", "isActive": false }')
,('LC', 'WARR', 'Warrington borough council', null, '{"issuingAuthorityShortCode":"WARR", "isActive": false }')
,('LC', 'WBERK', 'West Berkshire council', null, '{"issuingAuthorityShortCode":"WBERK", "isActive": false }')
,('LC', 'WIGAN', 'Wigan metropolitan borough council', null, '{"issuingAuthorityShortCode":"WIGAN", "isActive": false }')
,('LC', 'WILT', 'Wiltshire council', null, '{"issuingAuthorityShortCode":"WILT", "isActive": false }')
,('LC', 'WINMD', 'Royal borough of Windsor and Maidenhead', null, '{"issuingAuthorityShortCode":"WINMD", "isActive": false }')
,('LC', 'WIRR', 'Wirral borough council', null, '{"issuingAuthorityShortCode":"WIRR", "isActive": false }')
,('LC', 'WOK', 'Wokingham borough council', null, '{"issuingAuthorityShortCode":"WOK", "isActive": false }')
,('LC', 'WOLV', 'City of Wolverhampton council', null, '{"issuingAuthorityShortCode":"WOLV", "isActive": false }')
,('LC', 'WREX', 'Wrexham county borough council', null, '{"issuingAuthorityShortCode":"WREX", "isActive": false }')
,('LC', 'ADU', 'Adur district council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'ARU', 'Arun district council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'CHI', 'Chichester district council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'CRW', 'Crawley borough council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'HOR', 'Horsham district council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'MSS', 'Mid Sussex district council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'WSUCC', 'West Sussex county council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'WOT', 'Worthing borough council', null, '{"issuingAuthorityShortCode":"WSUCC", "isActive": false }')
,('LC', 'YORK', 'City of York council', null, '{"issuingAuthorityShortCode":"YORK", "isActive": false }');

-- //@UNDO
-- SQL to undo the change goes here.

update referencedata.reference_data set meta_data = meta_data::JSONB - 'isActive' where data_group_id = 'LC' and code in
('BRID', 'CAER', 'ESUCC', 'EAS', 'HAS', 'LEE', 'ROH', 'WEA', 'GLOCC', 'CHT',
'COT', 'FOE', 'GLS', 'STO', 'TEW', 'ANGL', 'KENTCC', 'ASF', 'CAT', 'DAR',
'DOV', 'SHE', 'GRA', 'MAI', 'SEV', 'SWL', 'THA', 'TON', 'TUN', 'LBEAL',
'NELIN', 'ABERD', 'EAYR', 'NAYR', 'SLAN', 'WDUN', 'WLOTH', 'WAKE', 'WORCC', 'BRM',
'MAV', 'RED', 'WOC', 'WYC', 'WYE', 'NWA', 'NUN', 'RUG', 'STR', 'WAW',
'WARCC', 'BAB', 'FOR', 'IPS', 'MSU', 'SED', 'SUF', 'SUFCC', 'WAV', 'BARNS');

DELETE FROM referencedata.reference_data WHERE data_group_id='LC' AND code IN (
'ABERC', 'ANGUS','ARBUT','BEDF', 'BIRM','BLACK','BLDRN','BLGW', 'BOLT', 'BOURN',
'BRAD','BRAFR','BRIHV','BRIST','BTNES','AYL','BUCCC','CHN','SBU','WYO',
'BURY','CALD','CAB','CAMCC','ECA','FEN','HUN','SCA','CARD','CARM',
'CBED','CERE','CHESE','CHEWC','CLACK','CONWY','CORN','COV','ALL','BAR',
'CAR','COP','CUMCC','EDN','SLA','DARL','DENB','DERBY','AMB','BOS',
'CHS','DERCC','DEB','ERE','HIG','NED','SDE','DEVCC','EDE','EXE',
'MDE','NDE','SHA','TEI','TOR','WDE','DONC','CHC','DORCC','EDO',
'NDO','PUR','WDO','WEY','DUDL','DUMGL','DUNDC','DURHM','EDIN','EDUN',
'EILSR','ELOTH','EREN','BAI','BRA','BRW','CAS','CHL','COL','EPP',
'ESSCC','HAR','MAL','ROC','TEN','UTT','EYORK','FALK','FIFE','FLINT',
'GATES','GLAM','GLAS','GWYN','HALT','BAN','EHA','EAT','FAR','GOS',
'HAMCC','HAT','HAA','NEW','RUH','TES','WIN','HART','BRX','DAC',
'EHE','HERCC','HER','NHE','SAL','STV','THE','WAT','WEW','HEREF',
'HIGH','HULL','INVC','IOS','IOW',
'KIRK','KNOWS',
'BUN','CHO','FYL','HYN','LANCC','LAC','PEN','PRE','RIB','ROS',
'SRI','WLA','WYR','LBBAD','LBBAR','LBBEX','LBBRE','LBBRO','LBCAM','LBCOL',
'LBCRO','LBENF','LBGRE','LBHAC','LBHAF','LBHAV','LBHGY','LBHIL','LBHOW','LBHRW',
'LBISL','LBKC','LBKUT','LBLAM','LBLEW','LBMER','LBNEW','LBRED','LBRIC','LBSOU',
'LBSUT','LBTHA','LBWAL','LBWAN','LBWES','LEEDS','LEIC','BLA','CHA','HAO',
'HIN','LEICC','MEL','NWL','OAD','BOT','LIC','ELI','LINCC','NKE',
'SHO','SKE','WLI','LIVER','LUTON','MANC','MEDTN','MERTH','MIDDL','MIDLH',
'MILKN','MON','MORAY',
'NEATH',
'NEWC','NEWP','ANN','AND','ABC',
'BFS','CCG','DRS','FMO','LBC','MEA','MUL','NIRE','NMD','NLAN',
'NLIN','KIN','BRE','BRO','GRY','NOFCC','NNO','NOW','SNO','COR',
'DAV','ENO','KET','NOR','NORCC','SNR','WEL','NORTH','ASH','BAE',
'BRT','GED','MAS','NEA','NOTCC','RUS','NOTT','NSOM','NTYNE','CRA',
'HAE','HAG','NYKCC','RIH','RYE','SCE','SEL','OLDH','ORKNY','CHR',
'OXO','OXFCC','SOX','VAL','WOX','PEMB','PERKN','PETBR','PLYM','POOLE',
'PORTS','POWYS','RCT','READ','REDCL','RENF','ROCH','ROTH','RUT','SALF',
'SAND','SAYR','SCBRD','SEFT','SEND','SGLCS','SHEFF','SHETL','SHROP','SLGH',
'SOLHL','MEN','SEG','SOMCC','SSO','TAU','WSO','SOUTH','CAN','EST',
'LIF','NEC','SST','STA','STACC','STF','TAW','STHEL','STIR','STOPT',
'STOTN','STOTR','STYNE','SUND','ELM','EPS','GRT','MOL','REI','RUN',
'SPE','SURCC','SUR','TAN','WAE','WOI','SWAN','SWIND','TAME','TELWK',
'THURK','TORB','TORF','TRAF','WAL','WARR','WBERK','WIGAN','WILT','WINMD',
'WIRR','WOK','WOLV','WREX','ADU','ARU','CHI','CRW','HOR','MSS',
'WSUCC','WOT','YORK');
