
-- // BBB-1026-update-la-meta-data
-- Migration SQL that makes the change goes here.

-- Generated from spreadsheet with following should this need to be done again...
-- =CONCAT("UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{""nameLine2"":""" ,TRIM(C2), """, ""addressLine1"":""", TRIM(D2)  , """, ""addressLine2"":""", TRIM(E2) , """, ""addressLine3"":""", TRIM(F2) , """, ""addressLine4"":""", TRIM(G2) , """, ""town"":""", TRIM(H2) , """, ""county"":""", TRIM(I2) , """, ""country"":""", TRIM(J2) , """, ""postcode"":""", TRIM(K2), """, ""contactNumber"":""", TRIM(L2), """, ""emailAddress"":""", TRIM(M2), """}' WHERE data_group_id='LA' AND code = '",A2,"';")
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Surrey County Council", "addressLine2":"Penrhyn Road", "addressLine3":"", "addressLine4":"", "town":"Kingston Upon Thames", "county":"Surrey", "country":"United Kingdom", "postcode":"KT1 2DN", "contactNumber":"", "emailAddress":"Blue.badges@surreycc.gov.uk"}' WHERE data_group_id='LA' AND code = 'SURCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Angus House", "addressLine2":"Orchardbank Business Park", "addressLine3":"", "addressLine4":"", "town":"Forfar", "county":"Angus", "country":"United Kingdom", "postcode":"DD8 1AN", "contactNumber":"03452777778", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'ANGUS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Quadrant East", "addressLine2":"1st Floor Right", "addressLine3":"16 The Silverlink North", "addressLine4":"", "town":"", "county":"North Tyneside", "country":"United Kingdom", "postcode":"NE27 0BY", "contactNumber":"03452000101", "emailAddress":"Blue.badges@northtyneside.gov.uk"}' WHERE data_group_id='LA' AND code = 'NTYNE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"10-16 Gibhill Road", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Greenock", "county":"Inverclyde", "country":"United Kingdom", "postcode":"PA15 2UP", "contactNumber":"01475714350", "emailAddress":"icil@inverclyde.gov.uk"}' WHERE data_group_id='LA' AND code = 'INVC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"1st floor", "addressLine2":"Hammersmith Town Hall Extension", "addressLine3":"King Street", "addressLine4":"", "town":"", "county":"London", "country":"United Kingdom", "postcode":"W6 9JU", "contactNumber":"02087536681", "emailAddress":"bluebadges@lbhf.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHAF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"1st Floor Wesley House", "addressLine2":"Corporation Street", "addressLine3":"", "addressLine4":"", "town":"St Helens", "county":"Merseyside", "country":"United Kingdom", "postcode":"WA10 1HP", "contactNumber":"01744676789", "emailAddress":"contactcentre@sthelens.gov.uk"}' WHERE data_group_id='LA' AND code = 'STHEL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"20 Whitehall Lane", "addressLine2":"Slade Green", "addressLine3":"", "addressLine4":"", "town":"Erith", "county":"Kent", "country":"United Kingdom", "postcode":"DA8 2DH", "contactNumber":"02030455329", "emailAddress":"nicola.francis@inspirecommunitytrust.org"}' WHERE data_group_id='LA' AND code = 'LBBEX';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"7 Brook Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Widnes", "county":"Cheshire", "country":"United Kingdom", "postcode":"WA8 6NB", "contactNumber":"01519078309", "emailAddress":"haltondirectlink@halton.gov.uk"}' WHERE data_group_id='LA' AND code = 'HALT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Assessible Transport", "addressLine1":"Community Services", "addressLine2":"Kensington & Chelsea Council Town Hall", "addressLine3":"Hornton Street", "addressLine4":"", "town":"", "county":"London", "country":"United Kingdom", "postcode":"W8 7NX", "contactNumber":"02073612390", "emailAddress":"accessible.transport@rbkc.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBKC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge", "addressLine1":"Room 210", "addressLine2":"Cardiff County Council", "addressLine3":"County Hall", "addressLine4":"Atlantic Wharf", "town":"Cardiff", "county":"", "country":"United Kingdom", "postcode":"CF10 4UW", "contactNumber":"02920872087", "emailAddress":"disabledbadges@cardiff.gov.uk"}' WHERE data_group_id='LA' AND code = 'CARD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Admin Team", "addressLine1":"Gun Wharf", "addressLine2":"Dock Road", "addressLine3":"", "addressLine4":"", "town":"Chatham", "county":"Kent", "country":"United Kingdom", "postcode":"ME4 4TR", "contactNumber":"01634333355", "emailAddress":"blue.badges@medway.gov.uk"}' WHERE data_group_id='LA' AND code = 'MEDTN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Administration", "addressLine1":"PO Box 873", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Oxford", "county":"Oxfordshire", "country":"United Kingdom", "postcode":"OX1 9NY", "contactNumber":"03450507666", "emailAddress":"bluebadgeadmin@oxfordshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'OXFCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Department", "addressLine1":"Adult Care Connect & Direct", "addressLine2":"Textile Hall", "addressLine3":"Manchester Road", "addressLine4":"", "town":"Bury", "county":"Lancashire", "country":"United Kingdom", "postcode":"BL9 0DG", "contactNumber":"01612536855", "emailAddress":"BlueBadges@bury.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'BURY';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"HSCP", "addressLine2":"Council Offices", "addressLine3":"16 Church Street", "addressLine4":"", "town":"Dumbarton", "county":"Dunbartonshire", "country":"United Kingdom", "postcode":"G82 1QL", "contactNumber":"01389776499", "emailAddress":"BlueBadgeAdministrator@wdc.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'WDUN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Comhairle nan Eilean Siar", "addressLine2":"Sandwick Road", "addressLine3":"Stornoway", "addressLine4":"", "town":"Isle of Lewis", "county":"Eilean Siar", "country":"United Kingdom", "postcode":"HS1 2BW", "contactNumber":"01851822708", "emailAddress":"bluebadgeteam@cne-siar.gsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'EILSR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Fife House", "addressLine2":"North Street", "addressLine3":"", "addressLine4":"", "town":"Glenrothes", "county":"Fife", "country":"United Kingdom", "postcode":"KY7 5LT", "contactNumber":"03451550066", "emailAddress":"European.parkingbadges@fife.gov.uk"}' WHERE data_group_id='LA' AND code = 'FIFE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Shropshire Council", "addressLine2":"The Shirehall (West Wing)", "addressLine3":"Abbey Foregate", "addressLine4":"", "town":"Shrewsbury", "county":"Shropshire", "country":"United Kingdom", "postcode":"SY2 6ND", "contactNumber":"03456789014", "emailAddress":"ss-bluebadge@shropshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'SHROP';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Room 1", "addressLine2":"Civic Centre", "addressLine3":"", "addressLine4":"", "town":"Poole", "county":"Dorset", "country":"United Kingdom", "postcode":"BH15 2RU", "contactNumber":"01202633605", "emailAddress":"bluebadges@poole.gov.uk"}' WHERE data_group_id='LA' AND code = 'POOLE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Post Room", "addressLine2":"Civic Centre", "addressLine3":"", "addressLine4":"", "town":"Southampton", "county":"", "country":"United Kingdom", "postcode":"SO14 7LY", "contactNumber":"02380832601", "emailAddress":"blue.badge@southampton.gov.uk"}' WHERE data_group_id='LA' AND code = 'SOUTH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Ley Street Depot", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Ilford", "county":"Essex", "country":"United Kingdom", "postcode":"IG2 7QZ", "contactNumber":"02085545000", "emailAddress":"bluebadgeteam@redbridge.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBRED';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Unit", "addressLine1":"PO Box 64", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"ENNISKILLEN", "county":"", "country":"United Kingdom", "postcode":"BT74 0BL", "contactNumber":"03002007818", "emailAddress":"bluebadges@infrastructure-ni.gov.uk"}' WHERE data_group_id='LA' AND code = 'NIRE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badges", "addressLine1":"Customer Contact Centre", "addressLine2":"Town Hall", "addressLine3":"St. Stephens Road", "addressLine4":"", "town":"Bournemouth", "county":"", "country":"United Kingdom", "postcode":"BH2 6EB", "contactNumber":"01202458744", "emailAddress":"blue.badges@bournemouth.gov.uk"}' WHERE data_group_id='LA' AND code = 'BOURN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Car Badge Team", "addressLine1":"Ground Floor", "addressLine2":"Sale Waterside", "addressLine3":"Waterside Plaza", "addressLine4":"", "town":"Sale", "county":"", "country":"United Kingdom", "postcode":"M33 7ZF", "contactNumber":"01619123000", "emailAddress":"Access.trafford@trafford.gov.uk"}' WHERE data_group_id='LA' AND code = 'TRAF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Burns House", "addressLine2":"Burns Statue Square", "addressLine3":"", "addressLine4":"", "town":"AYR", "county":"Ayrshire", "country":"United Kingdom", "postcode":"KA7 1UT", "contactNumber":"01292616261", "emailAddress":"DRCMail@south-ayrshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'SAYR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Business Support - Blue Badges", "addressLine1":"West Offices", "addressLine2":"Station Rise", "addressLine3":"", "addressLine4":"", "town":"York", "county":"North Yorkshire", "country":"United Kingdom", "postcode":"YO1 6GA", "contactNumber":"01904552522", "emailAddress":"bluebadge@york.gov.uk"}' WHERE data_group_id='LA' AND code = 'YORK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Camden Accessible Travel Solutions", "addressLine1":"London Borough of Camden", "addressLine2":"PO Box 64175", "addressLine3":"", "addressLine4":"", "town":"", "county":"London", "country":"United Kingdom", "postcode":"WC1A 9BY", "contactNumber":"02079745919", "emailAddress":"CATS@camden.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBCAM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Central Library & Customer Services Centre", "addressLine2":"Church Road", "addressLine3":"", "addressLine4":"", "town":"Stockton-on-Tees", "county":"", "country":"United Kingdom", "postcode":"TS18 1TU", "contactNumber":"01642528499", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'STOTN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre 2 West 08", "addressLine2":"High Street", "addressLine3":"", "addressLine4":"", "town":"Uxbridge", "county":"Middlesex", "country":"United Kingdom", "postcode":"UB8 1UW", "contactNumber":"01895556633", "emailAddress":"socialcaredirect@hillingdon.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHIL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Concessionary Travel Team", "addressLine1":"PO Box 70369", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"", "county":"LONDON", "country":"United Kingdom", "postcode":"SE1P 4RF", "contactNumber":"02075252146", "emailAddress":"disabledtravel@southwark.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBSOU';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Contact Centre", "addressLine1":"Royal Borough of Kingston upon Thames", "addressLine2":"Guildhall 2", "addressLine3":"", "addressLine4":"", "town":"Kingston upon Thames", "county":"Surrey", "country":"United Kingdom", "postcode":"KT1 1EU", "contactNumber":"02085475005", "emailAddress":"Adults@kingston.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBKUT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Contact Warrington", "addressLine1":"26-30 Horsemarket Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"WARRINGTON", "county":"", "country":"United Kingdom", "postcode":"WA1 1XL", "contactNumber":"01925443322", "emailAddress":"bluebadge@warrington.gov.uk"}' WHERE data_group_id='LA' AND code = 'WARR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Council Offices", "addressLine1":"Market Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Newbury", "county":"Berkshire", "country":"United Kingdom", "postcode":"RG14 5LD", "contactNumber":"01635503276", "emailAddress":"bluebadges@westberks.gov.uk"}' WHERE data_group_id='LA' AND code = 'WBERK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"County Hall", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Glenfield", "county":"Leicester", "country":"United Kingdom", "postcode":"LE3 8ST", "contactNumber":"01163050001", "emailAddress":"customerservices@leics.gov.uk"}' WHERE data_group_id='LA' AND code = 'LEICC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer & Communities", "addressLine1":"Customer Advice and Support Service", "addressLine2":"Council HQ", "addressLine3":"Newtown St Boswells", "addressLine4":"", "town":"Melrose", "county":"Scottish Borders", "country":"United Kingdom", "postcode":"TD6 0SA", "contactNumber":"03001001800", "emailAddress":"CustomerAdvice@scotborders.gov.uk"}' WHERE data_group_id='LA' AND code = 'SCBRD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Service (BB)", "addressLine1":"Blue Badge Team", "addressLine2":"St. Peters Square", "addressLine3":"Ground Floor Civic Centre", "addressLine4":"", "town":"Wolverhampton", "county":"", "country":"United Kingdom", "postcode":"WV1 1RL", "contactNumber":"01902551155", "emailAddress":"customer.services@wolverhampton.gov.uk"}' WHERE data_group_id='LA' AND code = 'WOLV';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Service Centre", "addressLine1":"PO Box 142", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Tiverton", "county":"Devon", "country":"United Kingdom", "postcode":"EX16 0BA", "contactNumber":"03451551006", "emailAddress":"csc.bluebadge@devon.gov.uk"}' WHERE data_group_id='LA' AND code = 'DEVCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Service Centre", "addressLine1":"P.O.Box 9320", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Nottingham", "county":"Notts", "country":"United Kingdom", "postcode":"NG15 5BL", "contactNumber":"03005008080", "emailAddress":"bluebadge@nottscc.gov.uk"}' WHERE data_group_id='LA' AND code = 'NOTCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Service Centre", "addressLine1":"One Angel Square", "addressLine2":"Angel Street", "addressLine3":"", "addressLine4":"", "town":"Northampton", "county":"Northamptonshire", "country":"United Kingdom", "postcode":"NN1 1ED", "contactNumber":"03001261000", "emailAddress":"bbmailroom@northamptonshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'NORCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Service Network", "addressLine1":"PO Box 1274", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Sunderland", "county":"", "country":"United Kingdom", "postcode":"SR5 9HN", "contactNumber":"01915205552", "emailAddress":"CSNFT@sunderland.gov.uk"}' WHERE data_group_id='LA' AND code = 'SUND';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services", "addressLine1":"Reception", "addressLine2":"10 Duke Street", "addressLine3":"", "addressLine4":"", "town":"Blackburn", "county":"Lancashire", "country":"United Kingdom", "postcode":"BB2 1DH", "contactNumber":"01254585381", "emailAddress":"bluebadges@blackburn.gov.uk"}' WHERE data_group_id='LA' AND code = 'BLDRN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services", "addressLine1":"Dundee House", "addressLine2":"50 North Lindsay Street", "addressLine3":"", "addressLine4":"", "town":"Dundee", "county":"", "country":"United Kingdom", "postcode":"DD1 1QE", "contactNumber":"01382438326", "emailAddress":"blue.badge@dundeecity.gov.uk"}' WHERE data_group_id='LA' AND code = 'DUNDC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services", "addressLine1":"Municipal Offices", "addressLine2":"Town Hall Square", "addressLine3":"", "addressLine4":"", "town":"Grimsby", "county":"North East Lincolnshire", "country":"United Kingdom", "postcode":"DN31 1HU", "contactNumber":"01472313131", "emailAddress":"Blue.Badge@nelincs.gov.uk"}' WHERE data_group_id='LA' AND code = 'NELIN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services", "addressLine1":"Clarence Arcade", "addressLine2":"Stamford Street", "addressLine3":"", "addressLine4":"", "town":"Ashton-under-Lyne", "county":"", "country":"United Kingdom", "postcode":"OL6 7PT", "contactNumber":"01613428355", "emailAddress":"customer.services@tameside.gov.uk"}' WHERE data_group_id='LA' AND code = 'TAME';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services", "addressLine1":"PO Box 700", "addressLine2":"Burton Street", "addressLine3":"", "addressLine4":"", "town":"Wakefield", "county":"", "country":"United Kingdom", "postcode":"WF1 2EB", "contactNumber":"03458506506", "emailAddress":"customerservices@wakefield.gov.uk"}' WHERE data_group_id='LA' AND code = 'WAKE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services Adminstration Team", "addressLine1":"PO Box 895", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Worcester", "county":"", "country":"United Kingdom", "postcode":"WR4 4FB", "contactNumber":"01905765765", "emailAddress":"bbadmin@worcestershire.gov.uk"}' WHERE data_group_id='LA' AND code = 'WORCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Development & Environment Services", "addressLine1":"Clackmannanshire Council", "addressLine2":"3rd Floor 1936 Building", "addressLine3":"Kilncraigs", "addressLine4":"Greenside Street", "town":"Alloa", "county":"Clackmannanshire", "country":"United Kingdom", "postcode":"FK10 1EB", "contactNumber":"01259450000", "emailAddress":"ptu@clacks.gov.uk"}' WHERE data_group_id='LA' AND code = 'CLACK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Development Services", "addressLine1":"Abbotsford House", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Davids Loan", "county":"FALKIRK", "country":"United Kingdom", "postcode":"FK2 7YZ", "contactNumber":"01324504975", "emailAddress":"adteam3.ds@falkirk.gov.uk"}' WHERE data_group_id='LA' AND code = 'FALK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Director for Adult and Community Service", "addressLine1":"County Hall", "addressLine2":"Colliton Park", "addressLine3":"", "addressLine4":"", "town":"Dorchester", "county":"Dorset", "country":"United Kingdom", "postcode":"DT1 1XJ", "contactNumber":"01305224321", "emailAddress":"parkingbadges@dorsetcc.gov.uk"}' WHERE data_group_id='LA' AND code = 'DORCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Disabled Travel", "addressLine1":"P.O. Box 1661", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Huddersfield", "county":"West Yorkshire", "country":"United Kingdom", "postcode":"HD1 9SR", "contactNumber":"01484414847", "emailAddress":"disabled.travel@kirklees.gov.uk"}' WHERE data_group_id='LA' AND code = 'KIRK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"DPB Team", "addressLine1":"1st Floor", "addressLine2":"Shute End", "addressLine3":"", "addressLine4":"", "town":"Wokingham", "county":"Berkshire", "country":"United Kingdom", "postcode":"RG40 1BN", "contactNumber":"01189746811", "emailAddress":"dpb@wokingham.gov.uk"}' WHERE data_group_id='LA' AND code = 'WOK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"East Network Team", "addressLine1":"Adults Social Services", "addressLine2":"Hewson House", "addressLine3":"Station Road", "addressLine4":"", "town":"Brigg", "county":"North Lincolnshire", "country":"United Kingdom", "postcode":"DN20 8XY", "contactNumber":"01724296981", "emailAddress":"east.networkadmin@northlincs.gov.uk"}' WHERE data_group_id='LA' AND code = 'NLIN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Essex House", "addressLine2":"200 The Crescent", "addressLine3":"Colchester Business Park", "addressLine4":"", "town":"Colchester", "county":"Essex", "country":"United Kingdom", "postcode":"CO4 9YQ", "contactNumber":"03456037630", "emailAddress":"blue.badge@essex.gov.uk"}' WHERE data_group_id='LA' AND code = 'ESSCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Floor 2", "addressLine2":"Howden House", "addressLine3":"1 Union Street", "addressLine4":"", "town":"Sheffield", "county":"South Yorkshire", "country":"United Kingdom", "postcode":"S1 2SH", "contactNumber":"01142734567", "emailAddress":"customerservices@sheffield.gov.uk"}' WHERE data_group_id='LA' AND code = 'SHEFF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Harrrow Council", "addressLine2":"Civic Centre", "addressLine3":"P.o.Box 592", "addressLine4":"Station Road", "town":"Harrow", "county":"Middlesex", "country":"United Kingdom", "postcode":"HA1 2XY", "contactNumber":"02089012680", "emailAddress":"concessionarytravel@harrow.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHRW';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Hereford Customer Service Centre", "addressLine2":"Blueschool House", "addressLine3":"Blueschool Street", "addressLine4":"", "town":"Hereford", "county":"Herefordshire", "country":"United Kingdom", "postcode":"HR1 2LX", "contactNumber":"01432260433", "emailAddress":"bluebadge@herefordshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'HEREF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Hertfordshire Blue Badge Scheme", "addressLine1":"PO Box 153", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Stevenage", "county":"", "country":"United Kingdom", "postcode":"SG1 2ST", "contactNumber":"03001234042", "emailAddress":"blue.badge@hertfordshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'HERCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Hove PIC", "addressLine1":"Room 217", "addressLine2":"Hove Town Hall", "addressLine3":"Norton Road", "addressLine4":"", "town":"Hove", "county":"", "country":"United Kingdom", "postcode":"BN3 3BQ", "contactNumber":"01273296270", "emailAddress":"bluebadgeparking@brighton-hove.gov.uk"}' WHERE data_group_id='LA' AND code = 'BRIHV';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"ISLINGTON PARKING SERVICES", "addressLine1":"BLUE BADGE TEAM", "addressLine2":"PO BOX 72951", "addressLine3":"", "addressLine4":"", "town":"", "county":"LONDON", "country":"United Kingdom", "postcode":"N7 1DL", "contactNumber":"02075276108", "emailAddress":"blue.badge@islington. gov.uk"}' WHERE data_group_id='LA' AND code = 'LBISL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"John Muir House", "addressLine2":"Brewery Lane", "addressLine3":"", "addressLine4":"", "town":"HADDINGTON", "county":"East Lothian", "country":"United Kingdom", "postcode":"EH41 3HA", "contactNumber":"01620827827", "emailAddress":"bluebadge.admin@eastlothian.gov.uk"}' WHERE data_group_id='LA' AND code = 'ELOTH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Landmark Place", "addressLine2":"High Street", "addressLine3":"", "addressLine4":"", "town":"Slough", "county":"Berkshire", "country":"United Kingdom", "postcode":"SL1 1JL", "contactNumber":"01753475111", "emailAddress":"BlueBadgeTeam@slough.gov.uk"}' WHERE data_group_id='LA' AND code = 'SLGH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Let''s Talk Blue Badge Team", "addressLine1":"Clarendon", "addressLine2":"Will Mill Way", "addressLine3":"", "addressLine4":"", "town":"Hebburn", "county":"Tyne and Wear", "country":"United Kingdom", "postcode":"NE31 1AT", "contactNumber":"01914246000", "emailAddress":"BlueBadge@southtyneside.gov.uk"}' WHERE data_group_id='LA' AND code = 'STYNE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Midlothian House", "addressLine2":"Buccleuch Street", "addressLine3":"", "addressLine4":"", "town":"Dalkeith", "county":"", "country":"United Kingdom", "postcode":"EH22 1DN", "contactNumber":"01315615455", "emailAddress":"jackie.young@midlothian.gov.uk"}' WHERE data_group_id='LA' AND code = 'MIDLH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Mobility Team", "addressLine1":"Waltham Forest Town Hall", "addressLine2":"Forest Road", "addressLine3":"", "addressLine4":"", "town":"Walthamstow", "county":"London", "country":"United Kingdom", "postcode":"E17 4JF", "contactNumber":"02084963000", "emailAddress":"Mobility.services@walthamforest.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBWAL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Moreton Library One Stop Shop", "addressLine1":"Pasture Road", "addressLine2":"Moreton", "addressLine3":"", "addressLine4":"", "town":"Wirral", "county":"Merseyside", "country":"United Kingdom", "postcode":"CH46 8SA", "contactNumber":"01516062006", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'WIRR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 657", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Leeds", "county":"", "country":"United Kingdom", "postcode":"LS1 9BS", "contactNumber":"01132224444", "emailAddress":"bluebadge@leeds.gov.uk"}' WHERE data_group_id='LA' AND code = 'LEEDS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 100", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Wigan", "county":"", "country":"United Kingdom", "postcode":"WN1 3DS", "contactNumber":"01942489014", "emailAddress":"BlueBadgeServices@wigan.gov.uk"}' WHERE data_group_id='LA' AND code = 'WIGAN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 15825", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Oldbury", "county":"", "country":"United Kingdom", "postcode":"B69 9EL", "contactNumber":"01215692266", "emailAddress":"sandwell_enquiry@sandwell.gov.uk"}' WHERE data_group_id='LA' AND code = 'SAND';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 19073", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Motherwell", "county":"Lanarkshire", "country":"United Kingdom", "postcode":"ML1 9DP", "contactNumber":"01698403160", "emailAddress":"Bluebadges@northlan.gov.uk"}' WHERE data_group_id='LA' AND code = 'NLAN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 50", "addressLine2":"Civic Centre", "addressLine3":"Silver Street", "addressLine4":"", "town":"ENFIELD", "county":"Middlesex", "country":"United Kingdom", "postcode":"EN1 3XA", "contactNumber":"02083792228", "emailAddress":"ctravel@enfield.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBENF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 615", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Rochdale", "county":"Lancs", "country":"United Kingdom", "postcode":"OL16 9TF", "contactNumber":"03003038870", "emailAddress":"Bluebadge@rochdale.gov.uk"}' WHERE data_group_id='LA' AND code = 'ROCH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 622", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Crewe", "county":"", "country":"United Kingdom", "postcode":"CW1 9JH", "contactNumber":"03001235020", "emailAddress":"bluebadge@cheshireeast.gov.uk"}' WHERE data_group_id='LA' AND code = 'CHESE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Redcar & Cleveland House", "addressLine2":"Licensing & Parking", "addressLine3":"Kirkleatham Street", "addressLine4":"", "town":"Redcar", "county":"", "country":"United Kingdom", "postcode":"TS10 1RT", "contactNumber":"01642774774", "emailAddress":"Car_parking@redcar-cleveland.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'REDCL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"SMBC Blue Badge Team", "addressLine1":"ASC - Business Support", "addressLine2":"4th Floor", "addressLine3":"Stopford House", "addressLine4":"Piccadilly", "town":"Stockport", "county":"", "country":"United Kingdom", "postcode":"SK1 3XE", "contactNumber":"01614743422", "emailAddress":"blue.badges@stockport.gov.uk"}' WHERE data_group_id='LA' AND code = 'STOPT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"St Mary''s House", "addressLine2":"52 St Leonards Road", "addressLine3":"", "addressLine4":"", "town":"Eastbourne", "county":"East Sussex", "country":"United Kingdom", "postcode":"BN21 3UU", "contactNumber":"01323464244", "emailAddress":"Bluecarbadge@eastsussex.gov.uk"}' WHERE data_group_id='LA' AND code = 'ESUCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Swindon Borough Council Civic Annexe", "addressLine2":"Ground Floor", "addressLine3":"Euclid Street", "addressLine4":"", "town":"Swindon", "county":"Wiltshire", "country":"United Kingdom", "postcode":"SN1 2JH", "contactNumber":"01793463327", "emailAddress":"Parking@swindon.gov.uk"}' WHERE data_group_id='LA' AND code = 'SWIND';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"The Regent Centre", "addressLine2":"Regent Road", "addressLine3":"Hanley", "addressLine4":"", "town":"Stoke-on-Trent", "county":"Staffordshire", "country":"United Kingdom", "postcode":"ST1 3EG", "contactNumber":"01782237999", "emailAddress":"parking@stoke.gov.uk"}' WHERE data_group_id='LA' AND code = 'STOTR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Torbay & South Devon NHS Foundation Trust", "addressLine1":"Castle Circus Health Centre", "addressLine2":"Abbey Road", "addressLine3":"", "addressLine4":"", "town":"Torquay", "county":"", "country":"United Kingdom", "postcode":"TQ2 5YH", "contactNumber":"01803219700", "emailAddress":"bbis.tct@nhs.net"}' WHERE data_group_id='LA' AND code = 'TORF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Transport Planning Service", "addressLine1":"6 North Ness Business Park", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Lerwick", "county":"Shetland", "country":"United Kingdom", "postcode":"ZE1 0LZ", "contactNumber":"01595744868", "emailAddress":"elaine.park@shetland.gov.uk"}' WHERE data_group_id='LA' AND code = 'SHETL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Transport Strategy Service", "addressLine1":"Civic Centre", "addressLine2":"Regent Street", "addressLine3":"", "addressLine4":"", "town":"Gateshead", "county":"", "country":"United Kingdom", "postcode":"NE8 1HH", "contactNumber":"01914333636", "emailAddress":"bluebadgeassessments@gateshead.gov.uk"}' WHERE data_group_id='LA' AND code = 'GATES';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Travel Concessions", "addressLine1":"Room 10.19", "addressLine2":"City Chambers", "addressLine3":"329 High Street", "addressLine4":"", "town":"EDINBURGH", "county":"Midlothian", "country":"United Kingdom", "postcode":"EH1 1YJ", "contactNumber":"01314693891", "emailAddress":"travelconcessions@edinburgh.gov.uk"}' WHERE data_group_id='LA' AND code = 'EDIN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Wansbeck Square", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Ashington", "county":"Northumberland", "country":"United Kingdom", "postcode":"NE63 9XL", "contactNumber":"03456006400", "emailAddress":"Bluebadges@Northumberland.gov.uk"}' WHERE data_group_id='LA' AND code = 'NORTH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"West Lothian Civic Centre", "addressLine2":"Howden South Road", "addressLine3":"", "addressLine4":"", "town":"Livingston", "county":"West Lothian", "country":"United Kingdom", "postcode":"EH54 6FF", "contactNumber":"01506280000", "emailAddress":"crm.administration@westlothian.gov.uk"}' WHERE data_group_id='LA' AND code = 'WLOTH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Shared Services (Assessments)", "addressLine1":"Truro", "addressLine2":"PO Box 676", "addressLine3":"", "addressLine4":"", "town":"Truro", "county":"Cornwall", "country":"United Kingdom", "postcode":"TR1 9EQ", "contactNumber":"03001234121", "emailAddress":"travelassessment@cornwall.gov.uk"}' WHERE data_group_id='LA' AND code = 'CORN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Contact Centre", "addressLine1":"Invicta House", "addressLine2":"County Hall", "addressLine3":"", "addressLine4":"", "town":"Maidstone", "county":"Kent", "country":"United Kingdom", "postcode":"ME14 1XX", "contactNumber":"03000416262", "emailAddress":"bluebadgeteam@kent.gov.uk"}' WHERE data_group_id='LA' AND code = 'KENTCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"The Halewood Centre", "addressLine2":"", "addressLine3":"Roseheath Drive", "addressLine4":"", "town":"Halewood", "county":"Knowsley", "country":"United Kingdom", "postcode":"L26 9UH", "contactNumber":"01514896000", "emailAddress":"blue.badge@knowsley.gov.uk"}' WHERE data_group_id='LA' AND code = 'KNOWS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Service", "addressLine1":"P O Box 100", "addressLine2":"County Hall", "addressLine3":"", "addressLine4":"", "town":"Preston", "county":"Lancashire", "country":"United Kingdom", "postcode":"PR1 0LD", "contactNumber":"03001236736", "emailAddress":"BlueBadge.Admin@lancashire.gov.uk"}' WHERE data_group_id='LA' AND code = 'LANCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Customer Services Centre", "addressLine2":"91 Granby Street", "addressLine3":"", "addressLine4":"", "town":"Leicester", "county":"Leicestershire", "country":"United Kingdom", "postcode":"LE1 6FB", "contactNumber":"01164541000", "emailAddress":"bluebadge@leicester.gov.uk"}' WHERE data_group_id='LA' AND code = 'LEIC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"2nd Floor", "addressLine2":"Pavilion Buildings", "addressLine3":"99-105 Lord Street", "addressLine4":"", "town":"Southport", "county":"Merseyside", "country":"United Kingdom", "postcode":"PR8 1RJ", "contactNumber":"03451400845", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'SEFT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badges - Transport", "addressLine1":"Environment and Business Support", "addressLine2":"Civic Offices", "addressLine3":"", "addressLine4":"", "town":"Guildhall Square", "county":"Portsmouth", "country":"United Kingdom", "postcode":"PO1 2NE", "contactNumber":"02392688304", "emailAddress":"BlueBadges@portsmouthcc.gov.uk"}' WHERE data_group_id='LA' AND code = 'PORTS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"The Mobility Team", "addressLine1":"2nd Floor", "addressLine2":"The Woolwich Centre", "addressLine3":"35 Wellington Street", "addressLine4":"", "town":"Woolwich", "county":"London", "country":"United Kingdom", "postcode":"SE18 6HQ", "contactNumber":"02089212388", "emailAddress":"mobility-duty@royalgreenwich.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBGRE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Keynsham Civic Centre", "addressLine2":"Market Walk", "addressLine3":"", "addressLine4":"", "town":"BRISTOL", "county":"", "country":"United Kingdom", "postcode":"BS31 1FS", "contactNumber":"01225477133", "emailAddress":"blue_badge@bathnes.gov.uk"}' WHERE data_group_id='LA' AND code = 'BTNES';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Dept for Chief Executive & Corporate Resources", "addressLine1":"Concessionary Travel Team", "addressLine2":"PO Box 1953", "addressLine3":"", "addressLine4":"", "town":"Bristol", "county":"", "country":"United Kingdom", "postcode":"BS37 0DB", "contactNumber":"01454868004", "emailAddress":"contravel@southglos.gov.uk"}' WHERE data_group_id='LA' AND code = 'SGLCS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Parkhouse Building", "addressLine2":"Baron Way", "addressLine3":"Kingmoor Business Park", "addressLine4":"", "town":"Carlisle", "county":"", "country":"United Kingdom", "postcode":"CA6 4SJ", "contactNumber":"01228606060", "emailAddress":"blue.badge@cumbria.gov.uk"}' WHERE data_group_id='LA' AND code = 'CUMCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Floor 3 Zone E", "addressLine2":"Bernard Weatherill House", "addressLine3":"8 Mint Walk", "addressLine4":"", "town":"Croydon", "county":"", "country":"United Kingdom", "postcode":"CR0 1EA", "contactNumber":"02087267100", "emailAddress":"travel.service@croydon.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBCRO';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Service Centre", "addressLine1":"Shire Hall", "addressLine2":"Market Square", "addressLine3":"", "addressLine4":"", "town":"Warwick", "county":"", "country":"United Kingdom", "postcode":"CV34 4RL", "contactNumber":"01926410410", "emailAddress":"bluebadges@warwickshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'WARCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"County Offices", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Matlock", "county":"Derbyshire", "country":"United Kingdom", "postcode":"DE4 3AG", "contactNumber":"08456058058", "emailAddress":"BlueBadges@derbyshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'DERCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Brierley Hill Health and Social Care Centre", "addressLine2":"Venture Way", "addressLine3":"", "addressLine4":"", "town":"Brierley Hill", "county":"West Midlands", "country":"United Kingdom", "postcode":"DY5 1RU", "contactNumber":"03005550055", "emailAddress":"bluebadgeteam@dudley.gov.uk"}' WHERE data_group_id='LA' AND code = 'DUDL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Stirling Bus Station", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Goosecroft Road", "county":"Stirling", "country":"United Kingdom", "postcode":"FK8 1PF", "contactNumber":"01786237502", "emailAddress":"tcc@stirling.gov.uk"}' WHERE data_group_id='LA' AND code = 'STIR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Grants Section", "addressLine2":"PO Box 19", "addressLine3":"", "addressLine4":"", "town":"Glasgow", "county":"", "country":"United Kingdom", "postcode":"G2 1DU", "contactNumber":"01412874578", "emailAddress":"bluebadgeteam@glasgow.gov.uk"}' WHERE data_group_id='LA' AND code = 'GLAS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"211 Main Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Barrhead", "county":"Glasgow", "country":"United Kingdom", "postcode":"G78 1SY", "contactNumber":"01415773001", "emailAddress":"bluebadge@eastrenfrewshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'EREN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Hesters Way Library", "addressLine2":"Goldsmith Road", "addressLine3":"", "addressLine4":"", "town":"CHELTENHAM", "county":"Gloucestershire", "country":"United Kingdom", "postcode":"GL51 7RT", "contactNumber":"01242532302", "emailAddress":"bluebadge@gloucestershire.gov.uk"}' WHERE data_group_id='LA' AND code = 'GLOCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Beverley", "county":"", "country":"United Kingdom", "postcode":"HU17 9BA", "contactNumber":"01482393939", "emailAddress":"customer.services@eastriding.gov.uk"}' WHERE data_group_id='LA' AND code = 'EYORK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"19 Horton Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Halifax", "county":"West Yorkshire", "country":"United Kingdom", "postcode":"HX1 1QE", "contactNumber":"01422288011", "emailAddress":"bluebadges@calderdale.gov.uk"}' WHERE data_group_id='LA' AND code = 'CALD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Osprey House", "addressLine2":"Alness Point Business Park", "addressLine3":"", "addressLine4":"", "town":"Alness", "county":"Ross and Cromarty", "country":"United Kingdom", "postcode":"IV17 0UP", "contactNumber":"01349886604", "emailAddress":"blue.badge@highland.gov.uk"}' WHERE data_group_id='LA' AND code = 'HIGH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Council Offices", "addressLine2":"School Place", "addressLine3":"", "addressLine4":"", "town":"Kirkwall", "county":"Orkney", "country":"United Kingdom", "postcode":"KW15 1NY", "contactNumber":"01856873535", "emailAddress":"customerservice@orkney.gov.uk"}' WHERE data_group_id='LA' AND code = 'ORKNY';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Catmose House", "addressLine2":"Catmos Street", "addressLine3":"Oakham", "addressLine4":"", "town":"Rutland", "county":"", "country":"United Kingdom", "postcode":"LE15 6HP", "contactNumber":"01572758330", "emailAddress":"bluebadges@rutland.gov.uk"}' WHERE data_group_id='LA' AND code = 'RUT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Contact Wrexham", "addressLine2":"16 Lord Street", "addressLine3":"", "addressLine4":"", "town":"Wrexham", "county":"Clwyd", "country":"United Kingdom", "postcode":"LL11 1LG", "contactNumber":"01978292066", "emailAddress":"contact-us@wrexham.gov.uk"}' WHERE data_group_id='LA' AND code = 'WREX';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Blue Badge Service", "addressLine2":"County Offices", "addressLine3":"", "addressLine4":"", "town":"Newland", "county":"LINCOLN", "country":"United Kingdom", "postcode":"LN1 1YL", "contactNumber":"01522782232", "emailAddress":"DisabledCarParking@lincolnshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'LINCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Town Hall", "addressLine2":"George Street", "addressLine3":"", "addressLine4":"", "town":"LUTON", "county":"", "country":"United Kingdom", "postcode":"LU1 2BQ", "contactNumber":"01582510372", "emailAddress":"bluebadges@luton.gov.uk"}' WHERE data_group_id='LA' AND code = 'LUTON';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Watling House", "addressLine2":"High Street North", "addressLine3":"", "addressLine4":"", "town":"Dunstable", "county":"Bedfordshire", "country":"United Kingdom", "postcode":"LU6 1LF", "contactNumber":"03003008035", "emailAddress":"car.badges@centralbedfordshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'CBED';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Borough Hall", "addressLine2":"Cauldwell Street", "addressLine3":"", "addressLine4":"", "town":"Bedford", "county":"", "country":"United Kingdom", "postcode":"MK42 9AP", "contactNumber":"01234228588", "emailAddress":"blue.badges@bedford.gov.uk"}' WHERE data_group_id='LA' AND code = 'BEDF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Offices", "addressLine2":"1 Saxon Gate East", "addressLine3":"", "addressLine4":"", "town":"Central Milton Keynes", "county":"Buckinghamshire", "country":"United Kingdom", "postcode":"MK9 3EJ", "contactNumber":"01908253449", "emailAddress":"bluebadge@milton-keynes.gov.uk"}' WHERE data_group_id='LA' AND code = 'MILKN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"River Park House", "addressLine2":"225 High Road", "addressLine3":"", "addressLine4":"", "town":"", "county":"London", "country":"United Kingdom", "postcode":"N22 8HQ", "contactNumber":"02084891000", "emailAddress":"concessionary.travel@haringey.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHGY';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Blue Badge Permits", "addressLine2":"Civic Centre", "addressLine3":"", "addressLine4":"", "town":"Newcastle-upon-Tyne", "county":"Tyne and Wear", "country":"United Kingdom", "postcode":"NE1 8QH", "contactNumber":"01912787878", "emailAddress":"bluebadge@newcastle.gov.uk"}' WHERE data_group_id='LA' AND code = 'NEWC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Community Protection", "addressLine2":"PO Box 10169", "addressLine3":"", "addressLine4":"", "town":"Nottingham", "county":"Nottinghamshire", "country":"United Kingdom", "postcode":"NG1 9HS", "contactNumber":"01158761499", "emailAddress":"Blue.badges@nottinghamcity.gov.uk"}' WHERE data_group_id='LA' AND code = 'NOTT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO BOX 10605", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"NOTTINGHAM", "county":"", "country":"United Kingdom", "postcode":"NG6 6DT", "contactNumber":"01217382656", "emailAddress":"birmingham.bluebadge@northgateps.com"}' WHERE data_group_id='LA' AND code = 'BIRM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Burnet Building", "addressLine2":"St. John Street", "addressLine3":"", "addressLine4":"", "town":"CAMPBELTOWN", "county":"", "country":"United Kingdom", "postcode":"PA28 6BJ", "contactNumber":"01546605517", "emailAddress":"bluebadges@argyll-bute.gov.uk"}' WHERE data_group_id='LA' AND code = 'ARBUT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Sand Martin House", "addressLine2":"Bittern Way", "addressLine3":"", "addressLine4":"", "town":"PETERBOROUGH", "county":"", "country":"United Kingdom", "postcode":"PE2 8TY", "contactNumber":"01733452356", "emailAddress":"Blue.badges@peterborough.gov.uk"}' WHERE data_group_id='LA' AND code = 'PETBR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Blue Badge Team", "addressLine2":"Pullar House", "addressLine3":"35 Kinnoull Street", "addressLine4":"", "town":"Perth", "county":"", "country":"United Kingdom", "postcode":"PH1 5GD", "contactNumber":"01738477222", "emailAddress":"bluebadges@pkc.gov.uk"}' WHERE data_group_id='LA' AND code = 'PERKN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 237", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Newport", "county":"Isle of Wight", "country":"United Kingdom", "postcode":"PO30 9FN", "contactNumber":"01983823340", "emailAddress":"Blue.badge@iow.gov.uk"}' WHERE data_group_id='LA' AND code = 'IOW';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Offices", "addressLine2":"Bridge Street", "addressLine3":"", "addressLine4":"", "town":"Reading", "county":"", "country":"United Kingdom", "postcode":"RG1 2LU", "contactNumber":"01189372033", "emailAddress":"bluebadge@reading.gov.uk"}' WHERE data_group_id='LA' AND code = 'READ';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Dagenham Library", "addressLine2":"1 Church Elm Lane", "addressLine3":"", "addressLine4":"", "town":"Dagenham", "county":"Essex", "country":"United Kingdom", "postcode":"RM10 9QS", "contactNumber":"02082272334", "emailAddress":"sally.atkins@elevateeastlondon.co.uk"}' WHERE data_group_id='LA' AND code = 'LBBAD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Riverside House", "addressLine2":"Main Street", "addressLine3":"", "addressLine4":"", "town":"Rotherham", "county":"South Yorkshire", "country":"United Kingdom", "postcode":"S60 1AE", "contactNumber":"01709336010", "emailAddress":"CSC-BlueCarBadge@rotherham.gov.uk"}' WHERE data_group_id='LA' AND code = 'ROTH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Town Hall", "addressLine2":"St Ives Road", "addressLine3":"", "addressLine4":"", "town":"Maidenhead", "county":"Berkshire", "country":"United Kingdom", "postcode":"SL6 1RF", "contactNumber":"01628683800", "emailAddress":"Blue.Badges@rbwm.gov.uk"}' WHERE data_group_id='LA' AND code = 'WINMD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Offices", "addressLine2":"St. Nicholas Way", "addressLine3":"", "addressLine4":"", "town":"Sutton", "county":"Surrey", "country":"United Kingdom", "postcode":"SM1 1EA", "contactNumber":"02087704578", "emailAddress":"liberty@sutton.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBSUT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"Victoria Avenue", "addressLine3":"", "addressLine4":"", "town":"Southend-on-Sea", "county":"Essex", "country":"United Kingdom", "postcode":"SS2 6ER", "contactNumber":"01702215003", "emailAddress":"council@southend.gov.uk"}' WHERE data_group_id='LA' AND code = 'SEND';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"2 Staffordshire Place", "addressLine2":"Stafford", "addressLine3":"", "addressLine4":"", "town":"", "county":"", "country":"United Kingdom", "postcode":"ST16 2DH", "contactNumber":"03001118000", "emailAddress":"Blue.Badges@staffordshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'STACC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"Victoria Road", "addressLine3":"", "addressLine4":"", "town":"Hartlepool", "county":"Cleveland", "country":"United Kingdom", "postcode":"TS24 8AY", "contactNumber":"01429523331", "emailAddress":"customer.service@hartlepool.gov.uk"}' WHERE data_group_id='LA' AND code = 'HART';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"Darwall Street", "addressLine3":"", "addressLine4":"", "town":"WALSALL", "county":"", "country":"United Kingdom", "postcode":"WS1 1TP", "contactNumber":"01922653560", "emailAddress":"BlueBadges@walsall.gov.uk"}' WHERE data_group_id='LA' AND code = 'WAL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Adult and Health Services", "addressLine1":"PO Box 115", "addressLine2":"Council Offices", "addressLine3":"Green Lane", "addressLine4":"", "town":"Spennymoor", "county":"County Durham", "country":"United Kingdom", "postcode":"DL16 9BX", "contactNumber":"03000 269425", "emailAddress":"bluebadgescheme@durham.gov.uk"}' WHERE data_group_id='LA' AND code = 'DURHM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Adult Social Services and Housing", "addressLine1":"Disabled Parking Permits", "addressLine2":"PO Box 53", "addressLine3":"Town Hall", "addressLine4":"", "town":"Weston-Super-Mare", "county":"North Somerset", "country":"United Kingdom", "postcode":"BS23 1UJ", "contactNumber":"01275 888801", "emailAddress":"care.connect@n-somerset.gov.uk"}' WHERE data_group_id='LA' AND code = 'NSOM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Barry Leisure Centre", "addressLine1":"Greenwood Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Barry", "county":"South Glamorgan", "country":"United Kingdom", "postcode":"CF63 4JJ", "contactNumber":"01446 700111", "emailAddress":"C1V@valeofglamorgan.gov.uk"}' WHERE data_group_id='LA' AND code = 'GLAM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"West Sussex County Council Contact Centre", "addressLine2":"Durban House", "addressLine3":"Durban Road", "addressLine4":"", "town":"Bognor Regis", "county":"West Sussex", "country":"United Kingdom", "postcode":"PO22 9RE", "contactNumber":"01243 777653", "emailAddress":"blue.badges@westsussex.gov.uk"}' WHERE data_group_id='LA' AND code = 'WSUCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Wiltshire Council", "addressLine2":"Bythesea Road", "addressLine3":"", "addressLine4":"", "town":"Trowbridge", "county":"Wiltshire", "country":"United Kingdom", "postcode":"BA14 8JN", "contactNumber":"01225 713002", "emailAddress":"bluebadge@wiltshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'WILT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Unit", "addressLine1":"Customer Services", "addressLine2":"County Hall", "addressLine3":"", "addressLine4":"", "town":"Norwich", "county":"Norfolk", "country":"United Kingdom", "postcode":"NR1 2DH", "contactNumber":"01603 306100", "emailAddress":"bluebadgeunit@norfolk.gov.uk"}' WHERE data_group_id='LA' AND code = 'NOFCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badges", "addressLine1":"PO BOX 71", "addressLine2":"Llandrindod Wells", "addressLine3":"", "addressLine4":"", "town":"Powys", "county":"", "country":"United Kingdom", "postcode":"LD1 9AQ", "contactNumber":"01597 827466", "emailAddress":"customer@powys.gov.uk"}' WHERE data_group_id='LA' AND code = 'POWYS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badges", "addressLine1":"Time Square", "addressLine2":"Market Street", "addressLine3":"", "addressLine4":"", "town":"Bracknell", "county":"Berkshire", "country":"United Kingdom", "postcode":"RG12 1JD", "contactNumber":"01344 351464", "emailAddress":"BlueBadge@Bracknell-Forest.gov.uk"}' WHERE data_group_id='LA' AND code = 'BRAFR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"C2BG Contact Centre", "addressLine1":"Blaenau Gwent CBC", "addressLine2":"Civic Centre", "addressLine3":"", "addressLine4":"", "town":"Ebbw Vale", "county":"Blaenau Gwent", "country":"United Kingdom", "postcode":"NP23 6XB", "contactNumber":"01495 311556", "emailAddress":"info@blaenau-gwent.gov.uk"}' WHERE data_group_id='LA' AND code = 'BLGW';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Caley Court Resource Centre", "addressLine2":"Moorpark Road West", "addressLine3":"", "addressLine4":"", "town":"Stevenston", "county":"Ayrshire", "country":"United Kingdom", "postcode":"KA20 3HU", "contactNumber":"01294 476148", "emailAddress":"ILSBB@north-ayrshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'NAYR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Office", "addressLine2":"Waterdale", "addressLine3":"", "addressLine4":"", "town":"Doncaster", "county":"South Yorkshire", "country":"United Kingdom", "postcode":"DN1 3BU", "contactNumber":"01302 862549", "emailAddress":"general.enquiries@doncaster.gov.uk"}' WHERE data_group_id='LA' AND code = 'DONC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"County Hall", "addressLine2":"North Yorkshire County Council", "addressLine3":"", "addressLine4":"", "town":"Northallerton", "county":"North Yorks", "country":"United Kingdom", "postcode":"DL7 8AD", "contactNumber":"01609 780780", "emailAddress":"servicedeliveryteam@northyorks.gov.uk"}' WHERE data_group_id='LA' AND code = 'NYKCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Flintshire Connects", "addressLine1":"Buckley Library", "addressLine2":"Buckley Shopping Centre", "addressLine3":"Brunswick Road", "addressLine4":"", "town":"BUCKLEY", "county":"Flintshire", "country":"United Kingdom", "postcode":"CH7 2EF", "contactNumber":"01352 701304", "emailAddress":"flintshire.connects@flintshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'FLINT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Hackney Service Centre", "addressLine2":"1 Hillman Street", "addressLine3":"", "addressLine4":"", "town":"London", "county":"", "country":"United Kingdom", "postcode":"E8 1DY", "contactNumber":"0208356 6262", "emailAddress":"BlueBadgeteam@hackney.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHAC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Kirkiintilloch Community Hub", "addressLine1":"Wm Patrick Library Building", "addressLine2":"2-4 West High Street", "addressLine3":"", "addressLine4":"", "town":"Kirkintilloch", "county":"", "country":"United Kingdom", "postcode":"G66 1AD", "contactNumber":"0300 1234510", "emailAddress":"sharedservices.general@eastdunbarton.gov.uk"}' WHERE data_group_id='LA' AND code = 'EDUN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"One Stop Shop", "addressLine2":"Town Hall", "addressLine3":"", "addressLine4":"", "town":"Bolton", "county":"Greater Manchester", "country":"United Kingdom", "postcode":"BL1 1RU", "contactNumber":"01204 337266", "emailAddress":"csdbluebadges@bolton.gov.uk"}' WHERE data_group_id='LA' AND code = 'BOLT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"One Stop Shop", "addressLine2":"Neath Civic Centre", "addressLine3":"Water Street", "addressLine4":"", "town":"Neath", "county":"", "country":"United Kingdom", "postcode":"SA11 3QZ", "contactNumber":"01639 685995", "emailAddress":"ossteamleader@npt.gov.uk"}' WHERE data_group_id='LA' AND code = 'NEATH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Parking Services (Blue Badges)", "addressLine1":"", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Plymouth", "county":"", "country":"United Kingdom", "postcode":"PL1 3BJ", "contactNumber":"01752 668000", "emailAddress":"bluebadge@plymouth.gov.uk"}' WHERE data_group_id='LA' AND code = 'PLYM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Public Advice & Service Centre", "addressLine2":"The Liberty Shopping Centre", "addressLine3":"", "addressLine4":"", "town":"Romford", "county":"", "country":"United Kingdom", "postcode":"RM1 3RL", "contactNumber":"01708 431914", "emailAddress":"bluebadges@havering.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHAV';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Social Care", "addressLine1":"Health and Housing Department", "addressLine2":"3", "addressLine3":"Spilman Street", "addressLine4":"", "town":"Carmarthen", "county":"Carmarthenshire", "country":"United Kingdom", "postcode":"SA31 1LE", "contactNumber":"01267 234567", "emailAddress":"schbluebadges@carmarthenshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'CARM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Traffic Management Team", "addressLine1":"Business Hub 11", "addressLine2":"Level 2 West", "addressLine3":"Aberdeen City Council", "addressLine4":"Marischal College", "town":"Broad Street", "county":"Aberdeen", "country":"United Kingdom", "postcode":"AB10 1AB", "contactNumber":"01224 522599", "emailAddress":"disabledbadges@aberdeencity.gov.uk"}' WHERE data_group_id='LA' AND code = 'ABERC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Transport and Education", "addressLine1":"PO Box 1253", "addressLine2":"2nd Floor Britannia House", "addressLine3":"Hall Ings", "addressLine4":"", "town":"Bradford", "county":"West Yorkshire", "country":"United Kingdom", "postcode":"BD1 1HX", "contactNumber":"01274 438723", "emailAddress":"Transport.Concessions@bradford.gov.uk"}' WHERE data_group_id='LA' AND code = 'BRAD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Department", "addressLine1":"Government Buildings", "addressLine2":"Dinerth Road", "addressLine3":"Colwyn Bay", "addressLine4":"", "town":"Conwy", "county":"", "country":"United Kingdom", "postcode":"LL28 4UL", "contactNumber":"01492 577800", "emailAddress":"bluebadge@conwy.gov.uk"}' WHERE data_group_id='LA' AND code = 'CONWY';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Customer Services", "addressLine1":"Civic Centre", "addressLine2":"Angel Street", "addressLine3":"", "addressLine4":"", "town":"Bridgend", "county":"Mid Glamorgan", "country":"United Kingdom", "postcode":"CF31 4WB", "contactNumber":"01656 643643", "emailAddress":"csc.BlueBadges@bridgend.gov.uk"}' WHERE data_group_id='LA' AND code = 'BRID';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Ty Elai", "addressLine2":"Dinas Isaf East", "addressLine3":"Williamstown", "addressLine4":"", "town":"Tonypandy", "county":"Mid Glamorgan", "country":"United Kingdom", "postcode":"CF40 1NY", "contactNumber":"01443 442100", "emailAddress":"FirstResponseTeam@rctcbc.gov.uk"}' WHERE data_group_id='LA' AND code = 'RCT';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Penallta House", "addressLine2":"Tredomen Park", "addressLine3":"Ystrad Mynach", "addressLine4":"", "town":"Hengoed", "county":"Mid Glamorgan", "country":"United Kingdom", "postcode":"CF82 7PG", "contactNumber":"01443 866571", "emailAddress":"BLUEBADGEASDIT@caerphilly.gov.uk"}' WHERE data_group_id='LA' AND code = 'CAER';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Contact Centre", "addressLine1":"Chepstow Community Hub (formerly Library)", "addressLine2":"Manor Way", "addressLine3":"", "addressLine4":"", "town":"Chepstow", "county":"Monmouthshire", "country":"United Kingdom", "postcode":"NP16 5HZ", "contactNumber":"01633 644644", "emailAddress":"cherylaharris@monmouthshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'MON';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Dept", "addressLine1":"County Hall", "addressLine2":"Freemans Way", "addressLine3":"", "addressLine4":"", "town":"Haverfordwest", "county":"Pembrokeshire", "country":"United Kingdom", "postcode":"SA61 1TP", "contactNumber":"01437 764551", "emailAddress":"bluebadgeadmin2@pembrokeshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'PEMB';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Cyngor Gwynedd Council", "addressLine2":"Uned 2", "addressLine3":"Parc Busnes Eryri", "addressLine4":"Minffordd", "town":"Penrhyndeudraeth", "county":"Gwynedd", "country":"United Kingdom", "postcode":"LL48 6LD", "contactNumber":"01766 771000", "emailAddress":"bathodynglas@gwynedd.llyw.cymru"}' WHERE data_group_id='LA' AND code = 'GWYN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Municipal Buildings", "addressLine2":"Corporation Street", "addressLine3":"", "addressLine4":"", "town":"", "county":"Blackpool", "country":"United Kingdom", "postcode":"FY1 1NF", "contactNumber":"01253 477477", "emailAddress":"customer.first@blackpool.gov.uk"}' WHERE data_group_id='LA' AND code = 'BLACK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Merthyr Tydfil", "county":"Mid Glamorgan", "country":"United Kingdom", "postcode":"CF47 8AN", "contactNumber":"01685 725000", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'MERTH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Council House", "addressLine2":"Corporation Street", "addressLine3":"", "addressLine4":"", "town":"Derby", "county":"", "country":"United Kingdom", "postcode":"DE1 2FS", "contactNumber":"01332 642982", "emailAddress":"bluebadge@derby.gov.uk"}' WHERE data_group_id='LA' AND code = 'DERBY';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"King George V House", "addressLine2":"King George V Road", "addressLine3":"", "addressLine4":"", "town":"Amersham", "county":"Buckinghamshire", "country":"United Kingdom", "postcode":"HP6 5AW", "contactNumber":"01296 382902", "emailAddress":"bbt@buckscc.gov.uk"}' WHERE data_group_id='LA' AND code = 'BUCCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Hull Central Library", "addressLine2":"Albion Street", "addressLine3":"", "addressLine4":"", "town":"Hull", "county":"", "country":"United Kingdom", "postcode":"HU1 3TF", "contactNumber":"01482 300300", "emailAddress":"bluebadgeimprovementservice@hullcc.gov.uk"}' WHERE data_group_id='LA' AND code = 'HULL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"15 Strand Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"KILMARNOCK", "county":"", "country":"United Kingdom", "postcode":"KA1 1HU", "contactNumber":"01563 555433", "emailAddress":"bluebadge@east-ayrshire.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'EAYR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 62", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"RUTHIN", "county":"Denbighshire", "country":"United Kingdom", "postcode":"LL15 9AZ", "contactNumber":"01824 712433", "emailAddress":"blue.badge@denbighshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'DENB';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Social Services", "addressLine2":"Council Offices", "addressLine3":"", "addressLine4":"", "town":"Llangefni", "county":"Isle of Anglesey", "country":"United Kingdom", "postcode":"LL77 7TW", "contactNumber":"01248 750057", "emailAddress":"AnnRoberts3@ynysmon.gov.uk"}' WHERE data_group_id='LA' AND code = 'ANGL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Information Station", "addressLine2":"Queensway", "addressLine3":"", "addressLine4":"", "town":"Newport", "county":"South Wales", "country":"United Kingdom", "postcode":"NP20 9LX", "contactNumber":"01633 656656", "emailAddress":"Blue.Badge@newport.gov.uk"}' WHERE data_group_id='LA' AND code = 'NEWP';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"Pontypool", "addressLine3":"", "addressLine4":"", "town":"Torfaen", "county":"", "country":"United Kingdom", "postcode":"NP4 6YB", "contactNumber":"01495 762200", "emailAddress":"socialcarecalltorfaen@torfaen.gov.uk"}' WHERE data_group_id='LA' AND code = 'TORF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"Oystermouth Road", "addressLine3":"", "addressLine4":"", "town":"Swansea", "county":"Swansea", "country":"United Kingdom", "postcode":"SA1 3SN", "contactNumber":"01792 637366", "emailAddress":"carbadge@swansea.gov.uk"}' WHERE data_group_id='LA' AND code = 'SWAN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Canolfan Rheidol", "addressLine2":"Rhodfa Padarn", "addressLine3":"", "addressLine4":"", "town":"ABERYSTWYTH", "county":"Ceredigion", "country":"United Kingdom", "postcode":"SY23 3UE", "contactNumber":"01545 900333", "emailAddress":"bluebadges@ceredigion.gov.uk"}' WHERE data_group_id='LA' AND code = 'CERE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Darby House", "addressLine2":"Lawn Central", "addressLine3":"", "addressLine4":"", "town":"Telford", "county":"", "country":"United Kingdom", "postcode":"TF3 4JA", "contactNumber":"01952 383838", "emailAddress":"contact@telford.gov.uk"}' WHERE data_group_id='LA' AND code = 'TELWK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Town Hall", "addressLine2":"St. Mary''s", "addressLine3":"", "addressLine4":"", "town":"Isles of Scilly", "county":"", "country":"United Kingdom", "postcode":"TR21 0LW", "contactNumber":"01720 424474", "emailAddress":"jeanette.persich@scilly.gov.uk"}' WHERE data_group_id='LA' AND code = 'IOS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Assisted Travel", "addressLine1":"PO Box 6510", "addressLine2":"London Borough of Barnet", "addressLine3":"", "addressLine4":"", "town":"Coventry", "county":"", "country":"United Kingdom", "postcode":"CV6 9NF", "contactNumber":"020 8359 4131", "emailAddress":"Assisted.Travel@Barnet.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBBAR';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Scheme", "addressLine1":"County Hall", "addressLine2":"Taunton", "addressLine3":"", "addressLine4":"", "town":"Somerset", "county":"", "country":"United Kingdom", "postcode":"TA1 4DY", "contactNumber":"0300 123 2224", "emailAddress":"BlueBadgeScheme@somerset.gov.uk"}' WHERE data_group_id='LA' AND code = 'SOMCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"Chorley Road", "addressLine3":"Swinton", "addressLine4":"", "town":"Salford", "county":"", "country":"United Kingdom", "postcode":"M27 5DA", "contactNumber":"0161 793 2500", "emailAddress":"bluebadge@salford.gov.uk"}' WHERE data_group_id='LA' AND code = 'SALF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Concessionary Travel Unit", "addressLine1":"London Borough of Hounslow", "addressLine2":"Civic Centre", "addressLine3":"Lampton Road", "addressLine4":"", "town":"Hounslow", "county":"", "country":"United Kingdom", "postcode":"TW3 4DN", "contactNumber":"0208 583 3073", "emailAddress":"bluebadge@hounslow.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBHOW';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Contact Centre", "addressLine1":"City of London", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"London", "county":"", "country":"United Kingdom", "postcode":"EC2P 2EJ", "contactNumber":"0207 332 1548", "emailAddress":"Jake.smit@cityoflondon.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBCOL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Ealing Council BBA", "addressLine1":"PO Box 68276", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Ealing", "county":"London", "country":"United Kingdom", "postcode":"W5 9LQ", "contactNumber":"020 8825 8161", "emailAddress":"csprocessing@ealing.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBEAL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"East Ham Customer Service Centre and Library", "addressLine2":"328 Barking Road", "addressLine3":"", "addressLine4":"", "town":"East Ham", "county":"London", "country":"United Kingdom", "postcode":"E6 2RT", "contactNumber":"0208 430 2000", "emailAddress":"blue.badge@newham.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBNEW';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Harpurhey District Office", "addressLine2":"6 Moston Lane", "addressLine3":"", "addressLine4":"", "town":"Harpurhey", "county":"Manchester", "country":"United Kingdom", "postcode":"M9 4DD", "contactNumber":"0161 205 7321", "emailAddress":"bluebadge@manchester.gov.uk"}' WHERE data_group_id='LA' AND code = 'MANC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Oldham Care and Support Ltd", "addressLine1":"The Blue Badge Team", "addressLine2":"The Link Centre", "addressLine3":"140 Union Street", "addressLine4":"", "town":"Oldham", "county":"Lancashire", "country":"United Kingdom", "postcode":"OL1 1DZ", "contactNumber":"0161 770 1222", "emailAddress":"bluebadgeteam@oldham.gov.uk"}' WHERE data_group_id='LA' AND code = 'OLDH';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Parking Permissions", "addressLine1":"PO Box 734", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Redhill", "county":"", "country":"United Kingdom", "postcode":"RH1 9FP", "contactNumber":"0207 823 4567", "emailAddress":"parkingpermits@westminster.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBWES';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 4206", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"London", "county":"", "country":"United Kingdom", "postcode":"SE6 4BR", "contactNumber":"020 8314 9844", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'LBLEW';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"SMBC Offices", "addressLine2":"West Mall", "addressLine3":"Chelmsley Wood", "addressLine4":"", "town":"Solihull", "county":"West Midlands", "country":"United Kingdom", "postcode":"B37 5TN", "contactNumber":"0121 704 6000", "emailAddress":"bluebadges@solihull.gov.uk"}' WHERE data_group_id='LA' AND code = 'SOLHL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"The Opal Assessment and Demonstration Centre", "addressLine2":"Unit 17-18 Bishopsgate Business Park", "addressLine3":"Widdrington Rd", "addressLine4":"", "town":"Coventry", "county":"", "country":"United Kingdom", "postcode":"CV1 4NA", "contactNumber":"0808 5834 333", "emailAddress":"bluebadge@coventry.gov.uk"}' WHERE data_group_id='LA' AND code = 'COV';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badges", "addressLine1":"Box Number: SH1015", "addressLine2":"Shire Hall", "addressLine3":"", "addressLine4":"", "town":"Cambridge", "county":"Cambridgeshire", "country":"United Kingdom", "postcode":"CB3 0AP", "contactNumber":"0345 045 5204", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'CAMCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO Box 18533", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Inverurie", "county":"Aberdeenshire", "country":"United Kingdom", "postcode":"AB51 5WX", "contactNumber":"03456 08 1208", "emailAddress":"bluebadge@aberdeenshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'ABERD';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Bromley Civic Centre", "addressLine2":"Stockwell Close", "addressLine3":"", "addressLine4":"", "town":"Bromley", "county":"", "country":"United Kingdom", "postcode":"BR1 3UH", "contactNumber":"0300 303 8661", "emailAddress":"BromleyLDS-Parking@liberata.com"}' WHERE data_group_id='LA' AND code = 'LBBRO';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Parking Services (Badges)", "addressLine1":"PO Box 3176", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Bristol", "county":"", "country":"United Kingdom", "postcode":"BS3 9FS", "contactNumber":"0117 922 2600", "emailAddress":"blue.badges@bristol.gov.uk"}' WHERE data_group_id='LA' AND code = 'BRIST';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Wyvern House", "addressLine2":"The Drumber", "addressLine3":"", "addressLine4":"", "town":"Winsford", "county":"Cheshire", "country":"United Kingdom", "postcode":"CW7 1AH", "contactNumber":"0300 123 7040", "emailAddress":"blue.badge@cheshirewestandchester.gov.uk"}' WHERE data_group_id='LA' AND code = 'CHEWC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Brent Civic Centre", "addressLine2":"Engineers Way", "addressLine3":"", "addressLine4":"", "town":"Wembley", "county":"Middlesex", "country":"United Kingdom", "postcode":"HA9 0FJ", "contactNumber":"0208 937 5796", "emailAddress":"Independenttravelteam@brent.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBBRE';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Parking Services", "addressLine2":"Cunard Buildings", "addressLine3":"Water Street", "addressLine4":"", "town":"Liverpool", "county":"", "country":"United Kingdom", "postcode":"L3 1AH", "contactNumber":"0151 233 3000", "emailAddress":"bluebadgeapplications@liverpool.gov.uk"}' WHERE data_group_id='LA' AND code = 'LIVER';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Cotton Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"Paisley", "county":"Renfrewshire", "country":"United Kingdom", "postcode":"PA1 1UJ", "contactNumber":"0300 300 0300", "emailAddress":"blue.badge@renfrewshire.gov.uk"}' WHERE data_group_id='LA' AND code = 'RENF';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Blue Badge and Concessionary Travel", "addressLine2":"PO Box 696", "addressLine3":"", "addressLine4":"", "town":"FAREHAM", "county":"Hampshire", "country":"United Kingdom", "postcode":"PO14 9PD", "contactNumber":"0300 555 1376", "emailAddress":"blue.badge@hants.gov.uk"}' WHERE data_group_id='LA' AND code = 'HAMCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Merton Civic Centre", "addressLine2":"London Road", "addressLine3":"", "addressLine4":"", "town":"Morden", "county":"Surrey", "country":"United Kingdom", "postcode":"SM4 5DX", "contactNumber":"020 8274 4901", "emailAddress":"concessionarytravel@merton.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBMER';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"OLIVE MORRIS HOUSE", "addressLine2":"18 BRIXTON HILL", "addressLine3":"", "addressLine4":"", "town":"BRIXTON", "county":"London", "country":"United Kingdom", "postcode":"SW2 1RD", "contactNumber":"020 7926 7777", "emailAddress":"accessibletransport@lambeth.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBLAM';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Centre", "addressLine2":"44 York Street", "addressLine3":"", "addressLine4":"", "town":"TWICKENHAM", "county":"", "country":"United Kingdom", "postcode":"TW1 3BZ", "contactNumber":"020 8831 6096", "emailAddress":"AccessibleTransport@richmond.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBRIC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Section", "addressLine1":"122-124 Irish Street", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"DUMFRIES", "county":"", "country":"United Kingdom", "postcode":"DG1 2PB", "contactNumber":"030 33 33 3001", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'DUMGL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Moray Resource Centre", "addressLine2":"Maisondieu Road", "addressLine3":"", "addressLine4":"", "town":"Elgin", "county":"Morayshire", "country":"United Kingdom", "postcode":"IV30 1RX", "contactNumber":"01343 547589", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'MORAY';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Civic Offices", "addressLine2":"New Road", "addressLine3":"", "addressLine4":"", "town":"Grays", "county":"Essex", "country":"United Kingdom", "postcode":"RM17 6SL", "contactNumber":"01375 366381", "emailAddress":"Blue.Badges@thurrock.gov.uk"}' WHERE data_group_id='LA' AND code = 'THURK';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Supported Travel Team", "addressLine1":"1st Floor Civic Centre", "addressLine2":"44 York Street", "addressLine3":"", "addressLine4":"", "town":"Twickenham", "county":"Surrey", "country":"United Kingdom", "postcode":"TW1 3BZ", "contactNumber":"02088 718238", "emailAddress":"DTSConcessionaryTravel@wandsworth.gov.uk"}' WHERE data_group_id='LA' AND code = 'LBWAN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Department of Social Care", "addressLine1":"Blue Badge Applications", "addressLine2":"PO Box 505", "addressLine3":"Civic Centre", "addressLine4":"", "town":"MIDDLESBROUGH", "county":"", "country":"United Kingdom", "postcode":"TS1 9FZ", "contactNumber":"01642 065070", "emailAddress":"socialservices@middlesbrough.gov.uk"}' WHERE data_group_id='LA' AND code = 'MIDDL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO BOX 3594", "addressLine2":"", "addressLine3":"", "addressLine4":"", "town":"", "county":"South Lanarkshire", "country":"United Kingdom", "postcode":"G73 9EG", "contactNumber":"03031231007", "emailAddress":"bluebadge@southlanarkshire.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'SLAN';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"Blue Badge Team", "addressLine1":"Barnsley MBC", "addressLine2":"PO Box 634", "addressLine3":"", "addressLine4":"", "town":"Barnsley", "county":"South Yorkshire", "country":"United Kingdom", "postcode":"S70 9GG", "contactNumber":"01226 773555", "emailAddress":"bluebadges@barnsley.gov.uk"}' WHERE data_group_id='LA' AND code = 'BARNS';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Room G01", "addressLine2":"Town Hall", "addressLine3":"", "addressLine4":"", "town":"Darlington", "county":"Co Durham", "country":"United Kingdom", "postcode":"DL1 5QT", "contactNumber":"01325 405222", "emailAddress":"customerservices@darlington.gov.uk"}' WHERE data_group_id='LA' AND code = 'DARL';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"PO BOX 258", "addressLine2":"Stowmarket", "addressLine3":"", "addressLine4":"", "town":"Ipswich", "county":"", "country":"United Kingdom", "postcode":"IP14 9BU", "contactNumber":"0808 800 4005", "emailAddress":"BlueBadgeTeam@suffolk.gcsx.gov.uk"}' WHERE data_group_id='LA' AND code = 'SUFCC';
UPDATE referencedata.reference_data SET meta_data = meta_data::JSONB || '{"nameLine2":"", "addressLine1":"Mulberry Place", "addressLine2":"5 Clove Crescent", "addressLine3":"", "addressLine4":"", "town":"", "county":"LONDON", "country":"United Kingdom", "postcode":"E14 2BG", "contactNumber":"0207 364 5003", "emailAddress":""}' WHERE data_group_id='LA' AND code = 'LBTHA';



-- //@UNDO
-- SQL to undo the change goes here.



update referencedata.reference_data
set meta_data = meta_data::JSONB - 'nameLine2'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'addressLine1'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'addressLine2'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'addressLine3'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'addressLine4'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'town'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'county'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'country'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'postcode'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'contactNumber'
where data_group_id='LA';

update referencedata.reference_data
set meta_data = meta_data::JSONB - 'emailAddress'
where data_group_id='LA';